  INFO root [0x00000da4] [2018-08-03 17:11:51,698] - 
  INFO root [0x00000da4] [2018-08-03 17:11:51,699] - -----------------------------------------------------------------------------------------


  INFO root [0x00000da4] [2018-08-03 17:11:51,701] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00000da4] [2018-08-03 17:11:51,701] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00000da4] [2018-08-03 17:11:51,701] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00000da4] [2018-08-03 17:11:51,709] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00000da4] [2018-08-03 17:11:51,728] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00000da4] [2018-08-03 17:11:51,732] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:3250 )
  INFO root [0x00000da4] [2018-08-03 17:11:51,732] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:3250, SOMAXCONN=128.
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - server-configs:
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - 	gameUpdateHertz : 10
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - 	entryScriptFile : kbemain
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - 	internalAddr : 10.139.66.192:3250
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00000da4] [2018-08-03 17:11:51,733] - 	componentID : 7001
  INFO root [0x00000da4] [2018-08-03 17:11:51,989] - Components::findLogger: found logger, addr:10.139.66.192:3142
  INFO root [0x00000da4] [2018-08-03 17:11:51,990] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00000da4] [2018-08-03 17:11:51,990] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00000da4] [2018-08-03 17:11:51,998] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 10796 ----
  INFO root [0x00000da4] [2018-08-03 17:11:51,998] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00000da4] [2018-08-03 17:11:51,999] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000da4] [2018-08-03 17:11:51,999] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,147] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,147] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,148] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,154] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,155] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,155] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,156] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000da4] [2018-08-03 17:11:52,217] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000da4] [2018-08-03 17:11:52,273] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00000da4] [2018-08-03 17:11:52,273] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,346] - loaded entity-script:Account(1).
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,397] - loaded entity-script:Avatar(2).
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,405] - loaded entity-script:Spaces(3).
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,412] - loaded entity-script:Space(4).
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,732] - loaded entity-script:Equipment(5).
 DEBUG root [0x00000da4] [2018-08-03 17:11:53,786] - loaded entity-script:Chat(6).
  INFO root [0x00000da4] [2018-08-03 17:11:53,786] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00000da4] [2018-08-03 17:11:53,786] - TelnetServer server is running on port 40000
  INFO root [0x00000da4] [2018-08-03 17:11:54,367] - ---- baseapp is running ----
 DEBUG root [0x00000da4] [2018-08-03 17:11:54,368] - Components::process(): Request for the process of identity...
  WARN root [0x00000da4] [2018-08-03 17:12:00,707] - Forwarding logs to logger[10.139.66.192:3142/0/0/0]...
 ERROR root [0x00000da4] [2018-08-03 17:12:35,000] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00000da4] [2018-08-03 17:12:35,005] - The following logs sent to logger failed:
  WARN root [0x00000da4] [2018-08-03 17:12:35,006] - ==> [2018-08-03 17:12:34 998] TCPPacketReceiver::processPendingEvents(10.139.66.192:3142): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00000da4] [2018-08-03 17:12:35,006] - ==> [2018-08-03 17:12:35 000] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00000da4] [2018-08-03 17:12:35,168] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
 ERROR root [0x00000da4] [2018-08-03 17:12:36,669] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00000da4] [2018-08-03 17:12:36,671] - Components::findComponents: receive error!
  WARN root [0x00000da4] [2018-08-03 17:12:36,672] - EntityApp::checkTickPeriod: tick took 1603% (1.60 seconds)!
  WARN root [0x00000da4] [2018-08-03 17:12:37,704] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
 ERROR root [0x00000da4] [2018-08-03 17:12:39,205] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00000da4] [2018-08-03 17:12:39,206] - Components::findComponents: receive error!
  WARN root [0x00000da4] [2018-08-03 17:12:39,207] - EntityApp::checkTickPeriod: tick took 1538% (1.54 seconds)!
  WARN root [0x00000da4] [2018-08-03 17:12:40,268] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
  INFO root [0x0000352c] [2018-08-03 17:12:45,372] - 
  INFO root [0x0000352c] [2018-08-03 17:12:45,372] - -----------------------------------------------------------------------------------------


  INFO root [0x0000352c] [2018-08-03 17:12:45,373] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000352c] [2018-08-03 17:12:45,374] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x0000352c] [2018-08-03 17:12:45,374] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000352c] [2018-08-03 17:12:45,383] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x0000352c] [2018-08-03 17:12:45,384] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x0000352c] [2018-08-03 17:12:45,390] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:3735 )
  INFO root [0x0000352c] [2018-08-03 17:12:45,390] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:3735, SOMAXCONN=128.
  INFO root [0x0000352c] [2018-08-03 17:12:45,391] - server-configs:
  INFO root [0x0000352c] [2018-08-03 17:12:45,391] - 	gameUpdateHertz : 10
  INFO root [0x0000352c] [2018-08-03 17:12:45,391] - 	entryScriptFile : kbemain
  INFO root [0x0000352c] [2018-08-03 17:12:45,391] - 	internalAddr : 10.139.66.192:3735
  INFO root [0x0000352c] [2018-08-03 17:12:45,392] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x0000352c] [2018-08-03 17:12:45,392] - 	componentID : 7001
  INFO root [0x0000352c] [2018-08-03 17:12:45,599] - Components::findLogger: found logger, addr:10.139.66.192:3696
  INFO root [0x0000352c] [2018-08-03 17:12:45,600] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x0000352c] [2018-08-03 17:12:45,600] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000352c] [2018-08-03 17:12:45,607] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 13580 ----
  INFO root [0x0000352c] [2018-08-03 17:12:45,608] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x0000352c] [2018-08-03 17:12:45,609] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000352c] [2018-08-03 17:12:45,610] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,757] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,758] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,759] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,762] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,763] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,763] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,764] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,818] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x0000352c] [2018-08-03 17:12:45,880] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x0000352c] [2018-08-03 17:12:45,880] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,927] - loaded entity-script:Account(1).
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,930] - loaded entity-script:Avatar(2).
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,932] - loaded entity-script:Spaces(3).
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,933] - loaded entity-script:Space(4).
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,949] - loaded entity-script:Equipment(5).
 DEBUG root [0x0000352c] [2018-08-03 17:12:45,952] - loaded entity-script:Chat(6).
  INFO root [0x0000352c] [2018-08-03 17:12:45,952] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000352c] [2018-08-03 17:12:45,953] - TelnetServer server is running on port 40000
  INFO root [0x0000352c] [2018-08-03 17:12:46,547] - ---- baseapp is running ----
 DEBUG root [0x0000352c] [2018-08-03 17:12:46,547] - Components::process(): Request for the process of identity...
  WARN root [0x0000352c] [2018-08-03 17:12:52,798] - Forwarding logs to logger[10.139.66.192:3696/0/0/0]...
 ERROR root [0x0000352c] [2018-08-03 17:13:57,969] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x0000352c] [2018-08-03 17:13:57,981] - The following logs sent to logger failed:
  WARN root [0x0000352c] [2018-08-03 17:13:57,982] - ==> [2018-08-03 17:13:57 969] TCPPacketReceiver::processPendingEvents(10.139.66.192:3696): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000352c] [2018-08-03 17:13:57,982] - ==> [2018-08-03 17:13:57 970] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x0000352c] [2018-08-03 17:13:58,107] - TCPPacketReceiver::processPendingEvents(10.139.66.192:3706): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000352c] [2018-08-03 17:13:58,108] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x0000352c] [2018-08-03 17:13:58,131] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000352c] [2018-08-03 17:13:58,134] - onBaseAppShutDown: state=0
  INFO root [0x0000352c] [2018-08-03 17:13:58,134] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000352c] [2018-08-03 17:13:58,134] - onBaseAppShutDown: state=1
  INFO root [0x0000352c] [2018-08-03 17:13:58,134] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000352c] [2018-08-03 17:13:58,134] - onBaseAppShutDown: state=2
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,160] - Spaces::~Spaces(): 3
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,160] - Chat::~Chat(): 2
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,162] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,162] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,162] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,162] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,162] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,163] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,163] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,163] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x0000352c] [2018-08-03 17:13:58,180] - Script::uninstall(): is successfully!
 DEBUG root [0x0000352c] [2018-08-03 17:13:58,181] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000352c] [2018-08-03 17:13:58,482] - ThreadPool::destroy(): waiting for thread(2)[0xb1fe0,0xb2048,], try=1
  INFO root [0x00000fec] [2018-08-03 17:14:00,758] - 
  INFO root [0x00000fec] [2018-08-03 17:14:00,758] - -----------------------------------------------------------------------------------------


  INFO root [0x00000fec] [2018-08-03 17:14:00,760] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00000fec] [2018-08-03 17:14:00,760] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00000fec] [2018-08-03 17:14:00,760] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00000fec] [2018-08-03 17:14:00,767] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00000fec] [2018-08-03 17:14:00,768] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00000fec] [2018-08-03 17:14:00,772] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:4371 )
  INFO root [0x00000fec] [2018-08-03 17:14:00,772] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:4371, SOMAXCONN=128.
  INFO root [0x00000fec] [2018-08-03 17:14:00,772] - server-configs:
  INFO root [0x00000fec] [2018-08-03 17:14:00,773] - 	gameUpdateHertz : 10
  INFO root [0x00000fec] [2018-08-03 17:14:00,773] - 	entryScriptFile : kbemain
  INFO root [0x00000fec] [2018-08-03 17:14:00,773] - 	internalAddr : 10.139.66.192:4371
  INFO root [0x00000fec] [2018-08-03 17:14:00,773] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00000fec] [2018-08-03 17:14:00,773] - 	componentID : 7001
  WARN root [0x00000fec] [2018-08-03 17:14:01,332] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20100, errorno=10048
  INFO root [0x00000fec] [2018-08-03 17:14:01,342] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 13816 ----
  INFO root [0x00000fec] [2018-08-03 17:14:01,343] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00000fec] [2018-08-03 17:14:01,344] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00000fec] [2018-08-03 17:14:01,344] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,505] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,506] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,507] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,513] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,513] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,514] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,515] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,585] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00000fec] [2018-08-03 17:14:01,644] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00000fec] [2018-08-03 17:14:01,645] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,707] - loaded entity-script:Account(1).
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,711] - loaded entity-script:Avatar(2).
 ERROR root [0x00000fec] [2018-08-03 17:14:01,729] - EntityDef::initialize: Could not load EntityModule[Spaces]
 S_ERR root [0x00000fec] [2018-08-03 17:14:01,731] - Traceback (most recent call last):
  File "D:/kbengine/assets_Battle of Gods/scripts/base\Spaces.py", line 5, in <module>
    import SCDefine
 S_ERR root [0x00000fec] [2018-08-03 17:14:01,732] -   File "D:/kbengine/assets_Battle of Gods/scripts/server_common\SCDefine.py", line 3, in <module>
    import GlobalConst
 S_ERR root [0x00000fec] [2018-08-03 17:14:01,732] - ImportError: No module named 'GlobalConst'
 ERROR root [0x00000fec] [2018-08-03 17:14:01,732] - app::initialize(): initialization failed!
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,734] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,735] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00000fec] [2018-08-03 17:14:01,751] - Script::uninstall(): is successfully!
 DEBUG root [0x00000fec] [2018-08-03 17:14:01,752] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00000fec] [2018-08-03 17:14:02,052] - ThreadPool::destroy(): waiting for thread(2)[0xc52758,0xc51d98,], try=1
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,461] - TPThread::~TPThread(): 0xc52758
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,461] - TPThread::~TPThread(): 0xc51d98
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,461] - ThreadPool::destroy(): successfully!
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,461] - Bundle::destroyObjPool(): size 14.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,461] - Channel::destroyObjPool(): size 0.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - UDPPacket::destroyObjPool(): size 15.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - Address::destroyObjPool(): size 0.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [0x00000fec] [2018-08-03 17:14:02,462] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [0x00000fec] [2018-08-03 17:14:08,965] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [0x000031d0] [2018-08-03 17:16:07,962] - 
  INFO root [0x000031d0] [2018-08-03 17:16:07,965] - -----------------------------------------------------------------------------------------


  INFO root [0x000031d0] [2018-08-03 17:16:07,967] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000031d0] [2018-08-03 17:16:07,967] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x000031d0] [2018-08-03 17:16:07,967] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000031d0] [2018-08-03 17:16:07,976] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x000031d0] [2018-08-03 17:16:07,977] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x000031d0] [2018-08-03 17:16:07,982] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:5497 )
  INFO root [0x000031d0] [2018-08-03 17:16:07,982] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:5497, SOMAXCONN=128.
  INFO root [0x000031d0] [2018-08-03 17:16:07,983] - server-configs:
  INFO root [0x000031d0] [2018-08-03 17:16:07,983] - 	gameUpdateHertz : 10
  INFO root [0x000031d0] [2018-08-03 17:16:07,983] - 	entryScriptFile : kbemain
  INFO root [0x000031d0] [2018-08-03 17:16:07,983] - 	internalAddr : 10.139.66.192:5497
  INFO root [0x000031d0] [2018-08-03 17:16:07,983] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x000031d0] [2018-08-03 17:16:07,984] - 	componentID : 7001
  INFO root [0x000031d0] [2018-08-03 17:16:08,479] - Components::findLogger: found logger, addr:10.139.66.192:5485
  INFO root [0x000031d0] [2018-08-03 17:16:08,479] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000031d0] [2018-08-03 17:16:08,479] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000031d0] [2018-08-03 17:16:08,488] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 7648 ----
  INFO root [0x000031d0] [2018-08-03 17:16:08,489] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x000031d0] [2018-08-03 17:16:08,490] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000031d0] [2018-08-03 17:16:08,490] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,649] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,650] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,651] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,660] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,661] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,661] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,662] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,751] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000031d0] [2018-08-03 17:16:08,821] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x000031d0] [2018-08-03 17:16:08,821] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,883] - loaded entity-script:Account(1).
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,886] - loaded entity-script:Avatar(2).
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,900] - loaded entity-script:Spaces(3).
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,902] - loaded entity-script:Space(4).
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,920] - loaded entity-script:Equipment(5).
 DEBUG root [0x000031d0] [2018-08-03 17:16:08,924] - loaded entity-script:Chat(6).
  INFO root [0x000031d0] [2018-08-03 17:16:08,924] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000031d0] [2018-08-03 17:16:08,925] - TelnetServer server is running on port 40000
  INFO root [0x000031d0] [2018-08-03 17:16:09,670] - ---- baseapp is running ----
 DEBUG root [0x000031d0] [2018-08-03 17:16:09,672] - Components::process(): Request for the process of identity...
  WARN root [0x000031d0] [2018-08-03 17:16:15,938] - Forwarding logs to logger[10.139.66.192:5485/0/0/0]...
 ERROR root [0x000031d0] [2018-08-03 17:16:50,332] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000031d0] [2018-08-03 17:16:50,338] - The following logs sent to logger failed:
  WARN root [0x000031d0] [2018-08-03 17:16:50,339] - ==> [2018-08-03 17:16:50 332] TCPPacketReceiver::processPendingEvents(10.139.66.192:5485): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000031d0] [2018-08-03 17:16:50,340] - ==> [2018-08-03 17:16:50 333] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
 S_ERR root [0x000031d0] [2018-08-03 17:16:50,372] - Traceback (most recent call last):
  File "D:/kbengine/assets_Battle of Gods/scripts/base\Spaces.py", line 51, in onTimer
    self.createSpaceOnTimer(tid)
 S_ERR root [0x000031d0] [2018-08-03 17:16:50,374] -   File "D:/kbengine/assets_Battle of Gods/scripts/base\Spaces.py", line 32, in createSpaceOnTimer
    if len(self._tmpDatas) > 0:
 S_ERR root [0x000031d0] [2018-08-03 17:16:50,378] - AttributeError: 'Spaces' object has no attribute '_tmpDatas'
  WARN root [0x000031d0] [2018-08-03 17:16:50,432] - TCPPacketReceiver::processPendingEvents(10.139.66.192:5494): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000031d0] [2018-08-03 17:16:50,434] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000031d0] [2018-08-03 17:16:50,451] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000031d0] [2018-08-03 17:16:50,459] - onBaseAppShutDown: state=0
  INFO root [0x000031d0] [2018-08-03 17:16:50,459] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000031d0] [2018-08-03 17:16:50,460] - onBaseAppShutDown: state=1
  INFO root [0x000031d0] [2018-08-03 17:16:50,460] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000031d0] [2018-08-03 17:16:50,461] - onBaseAppShutDown: state=2
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,484] - Spaces::~Spaces(): 3
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,484] - Chat::~Chat(): 2
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,486] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,486] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,486] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,487] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,487] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,487] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,487] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,487] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000031d0] [2018-08-03 17:16:50,503] - Script::uninstall(): is successfully!
 DEBUG root [0x000031d0] [2018-08-03 17:16:50,503] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000003e0] [2018-08-03 17:23:23,317] - 
  INFO root [0x000003e0] [2018-08-03 17:23:23,318] - -----------------------------------------------------------------------------------------


  INFO root [0x000003e0] [2018-08-03 17:23:23,319] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000003e0] [2018-08-03 17:23:23,320] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x000003e0] [2018-08-03 17:23:23,320] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000003e0] [2018-08-03 17:23:23,328] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x000003e0] [2018-08-03 17:23:23,329] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x000003e0] [2018-08-03 17:23:23,333] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:8886 )
  INFO root [0x000003e0] [2018-08-03 17:23:23,334] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:8886, SOMAXCONN=128.
  INFO root [0x000003e0] [2018-08-03 17:23:23,334] - server-configs:
  INFO root [0x000003e0] [2018-08-03 17:23:23,334] - 	gameUpdateHertz : 10
  INFO root [0x000003e0] [2018-08-03 17:23:23,334] - 	entryScriptFile : kbemain
  INFO root [0x000003e0] [2018-08-03 17:23:23,335] - 	internalAddr : 10.139.66.192:8886
  INFO root [0x000003e0] [2018-08-03 17:23:23,335] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x000003e0] [2018-08-03 17:23:23,335] - 	componentID : 7001
  INFO root [0x000003e0] [2018-08-03 17:23:23,822] - Components::findLogger: found logger, addr:10.139.66.192:8873
  INFO root [0x000003e0] [2018-08-03 17:23:23,822] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x000003e0] [2018-08-03 17:23:23,823] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000003e0] [2018-08-03 17:23:23,834] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 8812 ----
  INFO root [0x000003e0] [2018-08-03 17:23:23,835] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x000003e0] [2018-08-03 17:23:23,835] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000003e0] [2018-08-03 17:23:23,836] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x000003e0] [2018-08-03 17:23:23,996] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000003e0] [2018-08-03 17:23:23,997] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x000003e0] [2018-08-03 17:23:23,998] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,003] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,004] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,005] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,006] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,070] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x000003e0] [2018-08-03 17:23:24,130] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x000003e0] [2018-08-03 17:23:24,130] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,196] - loaded entity-script:Account(1).
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,198] - loaded entity-script:Avatar(2).
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,212] - loaded entity-script:Spaces(3).
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,214] - loaded entity-script:Space(4).
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,228] - loaded entity-script:Equipment(5).
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,232] - loaded entity-script:Chat(6).
  INFO root [0x000003e0] [2018-08-03 17:23:24,232] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000003e0] [2018-08-03 17:23:24,233] - TelnetServer server is running on port 40000
  INFO root [0x000003e0] [2018-08-03 17:23:24,900] - ---- baseapp is running ----
 DEBUG root [0x000003e0] [2018-08-03 17:23:24,900] - Components::process(): Request for the process of identity...
  WARN root [0x000003e0] [2018-08-03 17:23:31,198] - Forwarding logs to logger[10.139.66.192:8873/0/0/0]...
 ERROR root [0x000003e0] [2018-08-03 17:23:54,604] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x000003e0] [2018-08-03 17:23:54,613] - The following logs sent to logger failed:
  WARN root [0x000003e0] [2018-08-03 17:23:54,614] - ==> [2018-08-03 17:23:54 603] TCPPacketReceiver::processPendingEvents(10.139.66.192:8873): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000003e0] [2018-08-03 17:23:54,615] - ==> [2018-08-03 17:23:54 605] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x000003e0] [2018-08-03 17:23:54,733] - TCPPacketReceiver::processPendingEvents(10.139.66.192:8876): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000003e0] [2018-08-03 17:23:54,735] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x000003e0] [2018-08-03 17:23:54,747] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000003e0] [2018-08-03 17:23:54,753] - onBaseAppShutDown: state=0
  INFO root [0x000003e0] [2018-08-03 17:23:54,753] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000003e0] [2018-08-03 17:23:54,753] - onBaseAppShutDown: state=1
  INFO root [0x000003e0] [2018-08-03 17:23:54,753] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000003e0] [2018-08-03 17:23:54,754] - onBaseAppShutDown: state=2
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,781] - Spaces::~Spaces(): 3
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,782] - Chat::~Chat(): 2
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,785] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,786] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,786] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,786] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,786] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,787] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,787] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,787] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x000003e0] [2018-08-03 17:23:54,815] - Script::uninstall(): is successfully!
 DEBUG root [0x000003e0] [2018-08-03 17:23:54,816] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002d58] [2018-08-03 17:24:14,829] - 
  INFO root [0x00002d58] [2018-08-03 17:24:14,830] - -----------------------------------------------------------------------------------------


  INFO root [0x00002d58] [2018-08-03 17:24:14,831] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002d58] [2018-08-03 17:24:14,831] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [0x00002d58] [2018-08-03 17:24:14,832] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002d58] [2018-08-03 17:24:14,840] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:20015 )
  INFO root [0x00002d58] [2018-08-03 17:24:14,840] - NetworkInterface::initialize(EXTERNAL): address 10.139.66.192:20015, SOMAXCONN=128.
  INFO root [0x00002d58] [2018-08-03 17:24:14,846] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.66.192 ( 10.139.66.192:9434 )
  INFO root [0x00002d58] [2018-08-03 17:24:14,846] - NetworkInterface::initialize(INTERNAL): address 10.139.66.192:9434, SOMAXCONN=128.
  INFO root [0x00002d58] [2018-08-03 17:24:14,846] - server-configs:
  INFO root [0x00002d58] [2018-08-03 17:24:14,847] - 	gameUpdateHertz : 10
  INFO root [0x00002d58] [2018-08-03 17:24:14,847] - 	entryScriptFile : kbemain
  INFO root [0x00002d58] [2018-08-03 17:24:14,847] - 	internalAddr : 10.139.66.192:9434
  INFO root [0x00002d58] [2018-08-03 17:24:14,847] - 	externalAddr : 10.139.66.192:20015
  INFO root [0x00002d58] [2018-08-03 17:24:14,847] - 	componentID : 7001
  INFO root [0x00002d58] [2018-08-03 17:24:15,088] - Components::findLogger: found logger, addr:10.139.66.192:9420
  INFO root [0x00002d58] [2018-08-03 17:24:15,088] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [0x00002d58] [2018-08-03 17:24:15,089] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002d58] [2018-08-03 17:24:15,117] - ---- baseapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: F9DFFB319FBADF35943ADF4D42C4718C. Config: Debug X86. Built: 16:27:53 Apr 30 2018. AppID: 7001. UID: 10103. PID: 7396 ----
  INFO root [0x00002d58] [2018-08-03 17:24:15,132] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [0x00002d58] [2018-08-03 17:24:15,132] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002d58] [2018-08-03 17:24:15,133] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,304] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,305] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,306] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,313] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,314] - Script::install_py_dlls(): PyInit_select
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,314] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,315] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,382] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [0x00002d58] [2018-08-03 17:24:15,448] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [0x00002d58] [2018-08-03 17:24:15,448] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,507] - loaded entity-script:Account(1).
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,511] - loaded entity-script:Avatar(2).
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,575] - loaded entity-script:Spaces(3).
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,576] - loaded entity-script:Space(4).
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,588] - loaded entity-script:Equipment(5).
 DEBUG root [0x00002d58] [2018-08-03 17:24:15,590] - loaded entity-script:Chat(6).
  INFO root [0x00002d58] [2018-08-03 17:24:15,590] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002d58] [2018-08-03 17:24:15,590] - TelnetServer server is running on port 40000
  INFO root [0x00002d58] [2018-08-03 17:24:16,330] - ---- baseapp is running ----
 DEBUG root [0x00002d58] [2018-08-03 17:24:16,331] - Components::process(): Request for the process of identity...
  WARN root [0x00002d58] [2018-08-03 17:24:22,679] - Forwarding logs to logger[10.139.66.192:9420/0/0/0]...
 ERROR root [0x00002d58] [2018-08-03 17:25:29,512] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [0x00002d58] [2018-08-03 17:25:29,512] - The following logs sent to logger failed:
  WARN root [0x00002d58] [2018-08-03 17:25:29,512] - ==> [2018-08-03 17:25:29 521] TCPPacketReceiver::processPendingEvents(10.139.66.192:9420): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002d58] [2018-08-03 17:25:29,512] - ==> [2018-08-03 17:25:29 522] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [0x00002d58] [2018-08-03 17:25:29,605] - TCPPacketReceiver::processPendingEvents(10.139.66.192:9421): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002d58] [2018-08-03 17:25:29,605] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [0x00002d58] [2018-08-03 17:25:29,621] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002d58] [2018-08-03 17:25:29,621] - onBaseAppShutDown: state=0
  INFO root [0x00002d58] [2018-08-03 17:25:29,621] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002d58] [2018-08-03 17:25:29,621] - onBaseAppShutDown: state=1
  INFO root [0x00002d58] [2018-08-03 17:25:29,621] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002d58] [2018-08-03 17:25:29,621] - onBaseAppShutDown: state=2
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2004
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2005
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2006
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2007
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2008
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Space::~Space(): 2009
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Spaces::~Spaces(): 2003
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Chat::~Chat(): 2002
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,652] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [0x00002d58] [2018-08-03 17:25:29,668] - Script::uninstall(): is successfully!
 DEBUG root [0x00002d58] [2018-08-03 17:25:29,668] - ThreadPool::destroy(): starting size 2.
