  INFO root [2018-04-30 18:11:27,250] - 
  INFO root [2018-04-30 18:11:27,250] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 18:11:27,252] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-04-30 18:11:27,252] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets/;D:/kbengine/assets/scripts/;D:/kbengine/assets/res/
  INFO root [2018-04-30 18:11:27,252] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 18:11:27,258] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:20013 )
  INFO root [2018-04-30 18:11:27,259] - NetworkInterface::initialize(EXTERNAL): address 10.1.9.9:20013, SOMAXCONN=128.
  INFO root [2018-04-30 18:11:27,358] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:21912 )
  INFO root [2018-04-30 18:11:27,359] - NetworkInterface::initialize(INTERNAL): address 10.1.9.9:21912, SOMAXCONN=128.
  INFO root [2018-04-30 18:11:27,359] - server-configs:
  INFO root [2018-04-30 18:11:27,359] - 	internalAddr : 10.1.9.9:21912
  INFO root [2018-04-30 18:11:27,359] - 	externalAddr : 10.1.9.9:20013
  INFO root [2018-04-30 18:11:27,359] - 	componentID : 9000
  INFO root [2018-04-30 18:15:57,590] - 
  INFO root [2018-04-30 18:15:57,591] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 18:15:57,592] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-04-30 18:15:57,592] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets/;D:/kbengine/assets/scripts/;D:/kbengine/assets/res/
  INFO root [2018-04-30 18:15:57,592] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 18:15:57,598] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:20013 )
  INFO root [2018-04-30 18:15:57,598] - NetworkInterface::initialize(EXTERNAL): address 10.1.9.9:20013, SOMAXCONN=128.
  INFO root [2018-04-30 18:15:57,602] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:22095 )
  INFO root [2018-04-30 18:15:57,602] - NetworkInterface::initialize(INTERNAL): address 10.1.9.9:22095, SOMAXCONN=128.
  INFO root [2018-04-30 18:15:57,602] - server-configs:
  INFO root [2018-04-30 18:15:57,603] - 	internalAddr : 10.1.9.9:22095
  INFO root [2018-04-30 18:15:57,603] - 	externalAddr : 10.1.9.9:20013
  INFO root [2018-04-30 18:15:57,603] - 	componentID : 9000
  INFO root [2018-04-30 18:15:57,841] - Components::findLogger: found logger, addr:10.1.9.9:22074
  INFO root [2018-04-30 18:15:57,841] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-04-30 18:15:57,841] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 18:16:02,458] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 10776 ----
  INFO root [2018-04-30 18:16:02,459] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-04-30 18:16:02,459] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-30 18:16:02,459] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-30 18:16:02,599] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 18:16:02,600] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 18:16:02,601] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 18:16:02,604] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 18:16:02,604] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 18:16:02,604] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 18:16:02,605] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 18:16:02,673] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 18:16:02,725] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-04-30 18:16:02,725] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-30 18:16:02,736] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-30 18:16:02,736] - TelnetServer server is running on port 31000
  INFO root [2018-04-30 18:16:03,269] - ---- loginapp is running ----
 DEBUG root [2018-04-30 18:16:03,270] - Components::process(): Request for the process of identity...
  WARN root [2018-04-30 18:16:09,577] - Forwarding logs to logger[10.1.9.9:22074/0/0/0]...
 ERROR root [2018-04-30 18:19:28,572] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 18:19:28,573] - The following logs sent to logger failed:
  WARN root [2018-04-30 18:19:28,574] - ==> [2018-04-30 18:19:28 571] TCPPacketReceiver::processPendingEvents(10.1.9.9:22074): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 18:19:28,574] - ==> [2018-04-30 18:19:28 573] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-04-30 18:19:28,681] - TCPPacketReceiver::processPendingEvents(10.1.9.9:22076): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 18:19:28,682] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 18:19:28,683] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-04-30 18:19:28,684] - onLoginAppShutDown()
  INFO root [2018-04-30 18:19:28,684] - Shutdowner::onShutdown: shutting down
  INFO root [2018-04-30 18:19:28,684] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 18:19:28,685] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 18:19:28,686] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 18:19:28,686] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 18:19:28,703] - Script::uninstall(): is successfully!
 DEBUG root [2018-04-30 18:19:28,704] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-04-30 18:19:29,004] - ThreadPool::destroy(): waiting for thread(2)[0x380de78,0x380e018,], try=1
  INFO root [2018-04-30 18:19:31,182] - 
  INFO root [2018-04-30 18:19:31,182] - -----------------------------------------------------------------------------------------


  INFO root [2018-04-30 18:19:31,183] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-04-30 18:19:31,183] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets/;D:/kbengine/assets/scripts/;D:/kbengine/assets/res/
  INFO root [2018-04-30 18:19:31,183] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-04-30 18:19:31,188] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:20013 )
  INFO root [2018-04-30 18:19:31,188] - NetworkInterface::initialize(EXTERNAL): address 10.1.9.9:20013, SOMAXCONN=128.
  INFO root [2018-04-30 18:19:31,191] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.1.9.9 ( 10.1.9.9:22228 )
  INFO root [2018-04-30 18:19:31,191] - NetworkInterface::initialize(INTERNAL): address 10.1.9.9:22228, SOMAXCONN=128.
  INFO root [2018-04-30 18:19:31,191] - server-configs:
  INFO root [2018-04-30 18:19:31,192] - 	internalAddr : 10.1.9.9:22228
  INFO root [2018-04-30 18:19:31,192] - 	externalAddr : 10.1.9.9:20013
  INFO root [2018-04-30 18:19:31,192] - 	componentID : 9000
  INFO root [2018-04-30 18:19:31,478] - Components::findLogger: found logger, addr:10.1.9.9:22222
  INFO root [2018-04-30 18:19:31,479] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-04-30 18:19:31,479] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-04-30 18:19:31,489] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 5936 ----
  INFO root [2018-04-30 18:19:31,489] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-04-30 18:19:31,490] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-04-30 18:19:31,491] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-04-30 18:19:31,634] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 18:19:31,635] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 18:19:31,635] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 18:19:31,639] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 18:19:31,639] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 18:19:31,639] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 18:19:31,640] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 18:19:31,698] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 18:19:31,760] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-04-30 18:19:31,760] - Script::install(): KBExtra is successfully!
S_INFO root [2018-04-30 18:19:31,763] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-04-30 18:19:31,763] - TelnetServer server is running on port 31000
  INFO root [2018-04-30 18:19:32,243] - ---- loginapp is running ----
 DEBUG root [2018-04-30 18:19:32,244] - Components::process(): Request for the process of identity...
  WARN root [2018-04-30 18:19:38,422] - Forwarding logs to logger[10.1.9.9:22222/0/0/0]...
 ERROR root [2018-04-30 18:20:52,306] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 18:20:52,308] - The following logs sent to logger failed:
  WARN root [2018-04-30 18:20:52,309] - ==> [2018-04-30 18:20:52 304] TCPPacketReceiver::processPendingEvents(10.1.9.9:22222): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 18:20:52,309] - ==> [2018-04-30 18:20:52 306] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-04-30 18:20:52,398] - TCPPacketReceiver::processPendingEvents(10.1.9.9:22223): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-04-30 18:20:52,399] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-04-30 18:20:52,401] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-04-30 18:20:52,405] - onLoginAppShutDown()
  INFO root [2018-04-30 18:20:52,405] - Shutdowner::onShutdown: shutting down
  INFO root [2018-04-30 18:20:52,405] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-04-30 18:20:52,406] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-04-30 18:20:52,406] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-04-30 18:20:52,406] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-04-30 18:20:52,406] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-04-30 18:20:52,407] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-04-30 18:20:52,407] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-04-30 18:20:52,407] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-04-30 18:20:52,407] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-04-30 18:20:52,429] - Script::uninstall(): is successfully!
 DEBUG root [2018-04-30 18:20:52,429] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-04-30 18:20:52,730] - ThreadPool::destroy(): waiting for thread(2)[0x38b65d8,0x38b6640,], try=1
