  INFO root [2018-05-13 09:05:39,797] - 
  INFO root [2018-05-13 09:05:39,798] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:05:39,800] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:05:39,800] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:05:39,800] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:05:39,807] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:05:39,822] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:05:39,826] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:8738 )
  INFO root [2018-05-13 09:05:39,826] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:8738, SOMAXCONN=128.
  INFO root [2018-05-13 09:05:39,827] - server-configs:
  INFO root [2018-05-13 09:05:39,827] - 	internalAddr : 10.139.100.106:8738
  INFO root [2018-05-13 09:05:39,827] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:05:39,827] - 	componentID : 9000
  INFO root [2018-05-13 09:05:55,345] - 
  INFO root [2018-05-13 09:05:55,346] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:05:55,347] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:05:55,348] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:05:55,348] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:05:55,354] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:05:55,355] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:05:55,358] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:8780 )
  INFO root [2018-05-13 09:05:55,359] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:8780, SOMAXCONN=128.
  INFO root [2018-05-13 09:05:55,359] - server-configs:
  INFO root [2018-05-13 09:05:55,359] - 	internalAddr : 10.139.100.106:8780
  INFO root [2018-05-13 09:05:55,360] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:05:55,360] - 	componentID : 9000
  INFO root [2018-05-13 09:05:55,671] - Components::findLogger: found logger, addr:10.139.100.106:8763
  INFO root [2018-05-13 09:05:55,671] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:05:55,672] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:05:59,159] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 8688 ----
  INFO root [2018-05-13 09:05:59,160] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:05:59,161] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:05:59,162] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:05:59,314] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:05:59,314] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:05:59,315] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:05:59,320] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:05:59,320] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:05:59,320] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:05:59,321] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:05:59,374] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:05:59,421] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:05:59,422] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:05:59,480] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:05:59,481] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:06:00,099] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:06:00,100] - Components::process(): Request for the process of identity...
  INFO root [2018-05-13 09:06:08,997] - 
  INFO root [2018-05-13 09:06:08,998] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:06:08,999] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:06:09,000] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:06:09,000] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:06:09,008] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:06:09,009] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:06:09,013] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:8795 )
  INFO root [2018-05-13 09:06:09,014] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:8795, SOMAXCONN=128.
  INFO root [2018-05-13 09:06:09,014] - server-configs:
  INFO root [2018-05-13 09:06:09,014] - 	internalAddr : 10.139.100.106:8795
  INFO root [2018-05-13 09:06:09,014] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:06:09,015] - 	componentID : 9000
  INFO root [2018-05-13 09:06:09,390] - Components::findLogger: found logger, addr:10.139.100.106:8789
  INFO root [2018-05-13 09:06:09,391] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:06:09,391] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:06:09,402] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 12360 ----
  INFO root [2018-05-13 09:06:09,402] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:06:09,403] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:06:09,403] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:06:09,571] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:06:09,572] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:06:09,573] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:06:09,580] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:06:09,580] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:06:09,580] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:06:09,582] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:06:09,660] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:06:09,711] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:06:09,711] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:06:09,714] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:06:09,715] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:06:10,341] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:06:10,341] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:06:16,756] - Forwarding logs to logger[10.139.100.106:8789/0/0/0]...
 ERROR root [2018-05-13 09:11:53,344] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:11:53,350] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:11:53,350] - ==> [2018-05-13 09:11:53 344] TCPPacketReceiver::processPendingEvents(10.139.100.106:8789): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:11:53,351] - ==> [2018-05-13 09:11:53 345] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:11:56,044] - 
  INFO root [2018-05-13 09:11:56,044] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:11:56,045] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:11:56,046] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:11:56,046] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:11:56,053] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:11:56,053] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:11:56,058] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9067 )
  INFO root [2018-05-13 09:11:56,059] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9067, SOMAXCONN=128.
  INFO root [2018-05-13 09:11:56,059] - server-configs:
  INFO root [2018-05-13 09:11:56,059] - 	internalAddr : 10.139.100.106:9067
  INFO root [2018-05-13 09:11:56,059] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:11:56,059] - 	componentID : 9000
  INFO root [2018-05-13 09:11:56,382] - Components::findLogger: found logger, addr:10.139.100.106:9061
  INFO root [2018-05-13 09:11:56,382] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:11:56,382] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:11:56,390] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 6696 ----
  INFO root [2018-05-13 09:11:56,390] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:11:56,390] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:11:56,391] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:11:56,552] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:11:56,552] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:11:56,553] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:11:56,557] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:11:56,557] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:11:56,558] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:11:56,558] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:11:56,615] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:11:56,671] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:11:56,671] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:11:56,674] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:11:56,675] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:11:57,465] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:11:57,465] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:12:03,816] - Forwarding logs to logger[10.139.100.106:9061/0/0/0]...
 ERROR root [2018-05-13 09:12:10,572] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:12:10,574] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:12:10,574] - ==> [2018-05-13 09:12:10 572] TCPPacketReceiver::processPendingEvents(10.139.100.106:9061): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:12:10,575] - ==> [2018-05-13 09:12:10 573] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:12:11,065] - Components::findComponents: find dbmgr(4)...
  INFO root [2018-05-13 09:12:29,324] - 
  INFO root [2018-05-13 09:12:29,325] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:12:29,326] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:12:29,326] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:12:29,326] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:12:29,332] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:12:29,333] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:12:29,336] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9088 )
  INFO root [2018-05-13 09:12:29,337] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9088, SOMAXCONN=128.
  INFO root [2018-05-13 09:12:29,337] - server-configs:
  INFO root [2018-05-13 09:12:29,337] - 	internalAddr : 10.139.100.106:9088
  INFO root [2018-05-13 09:12:29,337] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:12:29,337] - 	componentID : 9000
  INFO root [2018-05-13 09:12:29,700] - Components::findLogger: found logger, addr:10.139.100.106:9082
  INFO root [2018-05-13 09:12:29,701] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:12:29,701] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:12:29,714] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 1064 ----
  INFO root [2018-05-13 09:12:29,714] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:12:29,715] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:12:29,715] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:12:29,899] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:12:29,900] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:12:29,901] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:12:29,911] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:12:29,912] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:12:29,913] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:12:29,914] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:12:29,986] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:12:30,044] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:12:30,044] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:12:30,048] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:12:30,048] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:12:30,638] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:12:30,639] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:12:37,039] - Forwarding logs to logger[10.139.100.106:9082/0/0/0]...
 ERROR root [2018-05-13 09:13:03,886] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:13:03,887] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:13:03,887] - ==> [2018-05-13 09:13:03 886] TCPPacketReceiver::processPendingEvents(10.139.100.106:9082): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:13:03,887] - ==> [2018-05-13 09:13:03 887] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:13:05,847] - 
  INFO root [2018-05-13 09:13:05,848] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:13:05,848] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:13:05,848] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:13:05,849] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:13:05,854] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:13:05,854] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:13:05,858] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9112 )
  INFO root [2018-05-13 09:13:05,859] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9112, SOMAXCONN=128.
  INFO root [2018-05-13 09:13:05,859] - server-configs:
  INFO root [2018-05-13 09:13:05,859] - 	internalAddr : 10.139.100.106:9112
  INFO root [2018-05-13 09:13:05,859] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:13:05,859] - 	componentID : 9000
  INFO root [2018-05-13 09:13:07,558] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 2572 ----
  INFO root [2018-05-13 09:13:07,559] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:13:07,560] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:13:07,560] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:13:07,724] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:13:07,725] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:13:07,725] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:13:07,729] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:13:07,729] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:13:07,730] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:13:07,730] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:13:07,795] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:13:07,860] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:13:07,860] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:13:07,864] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:13:07,864] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:13:08,428] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:13:08,429] - Components::process(): Request for the process of identity...
  INFO root [2018-05-13 09:13:15,759] - Components::findComponents: find logger(1)...
  INFO root [2018-05-13 09:13:15,836] - Components::findComponents: found logger, addr:10.139.100.106:9106
  INFO root [2018-05-13 09:13:15,837] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:13:15,838] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:13:15,842] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-05-13 09:13:15,955] - Components::findComponents: found dbmgr, addr:10.139.100.106:9107
  INFO root [2018-05-13 09:13:15,956] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:13:15,956] - Components::addComponent[dbmgr], uid=10103, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:13:15,957] - Components::findComponents: found dbmgr, addr:10.139.100.106:9107
  WARN root [2018-05-13 09:13:16,967] - Forwarding logs to logger[10.139.100.106:9106/0/0/0]...
 ERROR root [2018-05-13 09:30:46,786] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:30:46,789] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:30:46,790] - ==> [2018-05-13 09:30:46 785] TCPPacketReceiver::processPendingEvents(10.139.100.106:9106): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:30:46,790] - ==> [2018-05-13 09:30:46 787] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:30:46,897] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9107): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:30:46,898] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:30:46,900] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:30:46,901] - onLoginAppShutDown()
  INFO root [2018-05-13 09:30:46,902] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:30:46,902] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:30:46,902] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:30:46,903] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:30:46,903] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:30:46,903] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:30:46,903] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:30:46,903] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:30:46,904] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:30:46,904] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:30:46,919] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:30:46,919] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:30:47,225] - ThreadPool::destroy(): waiting for thread(2)[0x3b961d8,0x3b962a8,], try=1
  INFO root [2018-05-13 09:30:52,182] - 
  INFO root [2018-05-13 09:30:52,183] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:30:52,185] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:30:52,185] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:30:52,186] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:30:52,195] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:30:52,195] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:30:52,199] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9512 )
  INFO root [2018-05-13 09:30:52,200] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9512, SOMAXCONN=128.
  INFO root [2018-05-13 09:30:52,200] - server-configs:
  INFO root [2018-05-13 09:30:52,200] - 	internalAddr : 10.139.100.106:9512
  INFO root [2018-05-13 09:30:52,200] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:30:52,200] - 	componentID : 9000
  INFO root [2018-05-13 09:30:52,539] - Components::findLogger: found logger, addr:10.139.100.106:9495
  INFO root [2018-05-13 09:30:52,539] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:30:52,539] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:30:56,732] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 12212 ----
  INFO root [2018-05-13 09:30:56,733] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:30:56,734] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:30:56,735] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:30:56,897] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:30:56,898] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:30:56,899] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:30:56,906] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:30:56,906] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:30:56,906] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:30:56,908] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:30:56,979] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:30:57,031] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:30:57,032] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:30:57,035] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:30:57,036] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:30:57,714] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:30:57,714] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:31:04,094] - Forwarding logs to logger[10.139.100.106:9495/0/0/0]...
 ERROR root [2018-05-13 09:32:03,202] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:32:03,206] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:32:03,206] - ==> [2018-05-13 09:32:03 202] TCPPacketReceiver::processPendingEvents(10.139.100.106:9495): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:32:03,207] - ==> [2018-05-13 09:32:03 203] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:32:03,326] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9496): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:32:03,327] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:32:03,329] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:32:03,330] - onLoginAppShutDown()
  INFO root [2018-05-13 09:32:03,330] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:32:03,330] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:32:03,331] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:32:03,331] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:32:03,331] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:32:03,331] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:32:03,332] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:32:03,332] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:32:03,332] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:32:03,332] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:32:03,363] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:32:03,364] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:32:03,680] - ThreadPool::destroy(): waiting for thread(2)[0x3c8f668,0x3c8ee48,], try=1
  INFO root [2018-05-13 09:32:06,115] - 
  INFO root [2018-05-13 09:32:06,116] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:32:06,117] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:32:06,118] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:32:06,118] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:32:06,125] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:32:06,125] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:32:06,130] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9561 )
  INFO root [2018-05-13 09:32:06,130] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9561, SOMAXCONN=128.
  INFO root [2018-05-13 09:32:06,130] - server-configs:
  INFO root [2018-05-13 09:32:06,130] - 	internalAddr : 10.139.100.106:9561
  INFO root [2018-05-13 09:32:06,130] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:32:06,131] - 	componentID : 9000
  INFO root [2018-05-13 09:32:06,377] - Components::findLogger: found logger, addr:10.139.100.106:9555
  INFO root [2018-05-13 09:32:06,377] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:32:06,378] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:32:06,385] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 14524 ----
  INFO root [2018-05-13 09:32:06,385] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:32:06,386] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:32:06,386] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:32:06,563] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:32:06,564] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:32:06,564] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:32:06,570] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:32:06,595] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:32:06,596] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:32:06,597] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:32:06,670] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:32:06,731] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:32:06,732] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:32:06,735] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:32:06,735] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:32:07,308] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:32:07,309] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:32:13,778] - Forwarding logs to logger[10.139.100.106:9555/0/0/0]...
 ERROR root [2018-05-13 09:34:37,041] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:34:37,044] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:34:37,044] - ==> [2018-05-13 09:34:37 041] TCPPacketReceiver::processPendingEvents(10.139.100.106:9555): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:34:37,045] - ==> [2018-05-13 09:34:37 042] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:34:37,160] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:34:37,160] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:34:37,162] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:34:37,164] - onLoginAppShutDown()
  INFO root [2018-05-13 09:34:37,164] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:34:37,164] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:34:37,166] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:34:37,166] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:34:37,166] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:34:37,167] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:34:37,167] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:34:37,167] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:34:37,168] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:34:37,168] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:34:37,191] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:34:37,192] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:34:37,507] - ThreadPool::destroy(): waiting for thread(2)[0x3c423d8,0x3c421d0,], try=1
  INFO root [2018-05-13 09:34:39,915] - 
  INFO root [2018-05-13 09:34:39,915] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:34:39,916] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:34:39,917] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:34:39,917] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:34:39,924] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:34:39,924] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:34:39,928] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9710 )
  INFO root [2018-05-13 09:34:39,928] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9710, SOMAXCONN=128.
  INFO root [2018-05-13 09:34:39,928] - server-configs:
  INFO root [2018-05-13 09:34:39,928] - 	internalAddr : 10.139.100.106:9710
  INFO root [2018-05-13 09:34:39,928] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:34:39,928] - 	componentID : 9000
  INFO root [2018-05-13 09:34:40,258] - Components::findLogger: found logger, addr:10.139.100.106:9704
  INFO root [2018-05-13 09:34:40,259] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:34:40,259] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:34:40,270] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 15048 ----
  INFO root [2018-05-13 09:34:40,270] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:34:40,271] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:34:40,272] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:34:40,447] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:34:40,447] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:34:40,448] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:34:40,454] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:34:40,455] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:34:40,455] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:34:40,456] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:34:40,543] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:34:40,643] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:34:40,643] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:34:40,648] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:34:40,649] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:34:41,331] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:34:41,332] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:34:47,708] - Forwarding logs to logger[10.139.100.106:9704/0/0/0]...
 ERROR root [2018-05-13 09:35:18,510] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:35:18,514] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:35:18,516] - ==> [2018-05-13 09:35:18 509] TCPPacketReceiver::processPendingEvents(10.139.100.106:9704): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:35:18,516] - ==> [2018-05-13 09:35:18 511] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:35:18,635] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9705): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:35:18,637] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:35:18,643] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:35:18,643] - onLoginAppShutDown()
  INFO root [2018-05-13 09:35:18,643] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:35:18,644] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:35:18,644] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:35:18,644] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:35:18,645] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:35:18,645] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:35:18,645] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:35:18,645] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:35:18,645] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:35:18,646] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:35:18,659] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:35:18,660] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:35:18,967] - ThreadPool::destroy(): waiting for thread(2)[0x3ce1310,0x3ce0c90,], try=1
  INFO root [2018-05-13 09:35:21,361] - 
  INFO root [2018-05-13 09:35:21,362] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:35:21,363] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:35:21,363] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:35:21,364] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:35:21,369] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:35:21,370] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:35:21,374] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9749 )
  INFO root [2018-05-13 09:35:21,375] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9749, SOMAXCONN=128.
  INFO root [2018-05-13 09:35:21,375] - server-configs:
  INFO root [2018-05-13 09:35:21,375] - 	internalAddr : 10.139.100.106:9749
  INFO root [2018-05-13 09:35:21,375] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:35:21,375] - 	componentID : 9000
  INFO root [2018-05-13 09:35:21,601] - Components::findLogger: found logger, addr:10.139.100.106:9744
  INFO root [2018-05-13 09:35:21,601] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:35:21,602] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:35:21,609] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 6296 ----
  INFO root [2018-05-13 09:35:21,610] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:35:21,610] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:35:21,612] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:35:21,781] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:35:21,781] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:35:21,782] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:35:21,789] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:35:21,789] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:35:21,789] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:35:21,791] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:35:21,858] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:35:21,924] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:35:21,924] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:35:21,928] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:35:21,928] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:35:22,595] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:35:22,597] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:35:29,085] - Forwarding logs to logger[10.139.100.106:9744/0/0/0]...
 ERROR root [2018-05-13 09:38:15,870] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:38:15,876] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:38:15,876] - ==> [2018-05-13 09:38:15 869] TCPPacketReceiver::processPendingEvents(10.139.100.106:9744): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:38:15,877] - ==> [2018-05-13 09:38:15 871] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:38:16,039] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9745): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:38:16,041] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:38:16,044] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:38:16,046] - onLoginAppShutDown()
  INFO root [2018-05-13 09:38:16,046] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:38:16,046] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:38:16,047] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:38:16,047] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:38:16,048] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:38:16,048] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:38:16,048] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:38:16,049] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:38:16,049] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:38:16,049] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:38:16,075] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:38:16,076] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:38:16,391] - ThreadPool::destroy(): waiting for thread(2)[0x3c93880,0x3c937b0,], try=1
  INFO root [2018-05-13 09:38:18,818] - 
  INFO root [2018-05-13 09:38:18,818] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:38:18,819] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:38:18,820] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:38:18,820] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:38:18,825] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:38:18,826] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:38:18,830] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:9829 )
  INFO root [2018-05-13 09:38:18,830] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:9829, SOMAXCONN=128.
  INFO root [2018-05-13 09:38:18,830] - server-configs:
  INFO root [2018-05-13 09:38:18,831] - 	internalAddr : 10.139.100.106:9829
  INFO root [2018-05-13 09:38:18,831] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:38:18,831] - 	componentID : 9000
  INFO root [2018-05-13 09:38:19,111] - Components::findLogger: found logger, addr:10.139.100.106:9823
  INFO root [2018-05-13 09:38:19,112] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:38:19,112] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:38:19,119] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 12936 ----
  INFO root [2018-05-13 09:38:19,120] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:38:19,121] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:38:19,121] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:38:19,282] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:38:19,283] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:38:19,283] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:38:19,287] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:38:19,287] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:38:19,287] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:38:19,288] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:38:19,337] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:38:19,391] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:38:19,391] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:38:19,394] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:38:19,395] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:38:19,963] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:38:19,963] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:38:26,267] - Forwarding logs to logger[10.139.100.106:9823/0/0/0]...
 ERROR root [2018-05-13 09:56:41,083] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:56:41,085] - The following logs sent to logger failed:
  WARN root [2018-05-13 09:56:41,086] - ==> [2018-05-13 09:56:41 081] TCPPacketReceiver::processPendingEvents(10.139.100.106:9823): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:56:41,086] - ==> [2018-05-13 09:56:41 084] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 09:56:41,206] - TCPPacketReceiver::processPendingEvents(10.139.100.106:9824): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 09:56:41,208] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 09:56:41,209] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 09:56:41,209] - onLoginAppShutDown()
  INFO root [2018-05-13 09:56:41,210] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 09:56:41,210] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 09:56:41,211] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:56:41,211] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:56:41,211] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:56:41,211] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:56:41,211] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:56:41,212] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:56:41,212] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:56:41,212] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:56:41,227] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 09:56:41,227] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 09:56:41,529] - ThreadPool::destroy(): waiting for thread(2)[0x3b50c98,0x3b50dd0,], try=1
  INFO root [2018-05-13 09:56:43,768] - 
  INFO root [2018-05-13 09:56:43,769] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 09:56:43,770] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 09:56:43,771] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 09:56:43,771] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 09:56:43,780] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 09:56:43,780] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 09:56:43,785] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:10181 )
  INFO root [2018-05-13 09:56:43,785] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:10181, SOMAXCONN=128.
  INFO root [2018-05-13 09:56:43,785] - server-configs:
  INFO root [2018-05-13 09:56:43,785] - 	internalAddr : 10.139.100.106:10181
  INFO root [2018-05-13 09:56:43,785] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 09:56:43,786] - 	componentID : 9000
  INFO root [2018-05-13 09:56:44,063] - Components::findLogger: found logger, addr:10.139.100.106:10175
  INFO root [2018-05-13 09:56:44,064] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 09:56:44,064] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 09:56:44,074] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 652 ----
  INFO root [2018-05-13 09:56:44,075] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 09:56:44,075] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 09:56:44,076] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 09:56:44,224] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 09:56:44,225] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 09:56:44,225] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 09:56:44,230] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 09:56:44,231] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 09:56:44,231] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 09:56:44,233] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 09:56:44,298] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 09:56:44,351] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 09:56:44,351] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 09:56:44,355] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 09:56:44,356] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 09:56:45,122] - ---- loginapp is running ----
 DEBUG root [2018-05-13 09:56:45,123] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 09:56:51,581] - Forwarding logs to logger[10.139.100.106:10175/0/0/0]...
 ERROR root [2018-05-13 10:08:47,498] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 10:08:47,500] - The following logs sent to logger failed:
  WARN root [2018-05-13 10:08:47,501] - ==> [2018-05-13 10:08:47 498] TCPPacketReceiver::processPendingEvents(10.139.100.106:10175): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 10:08:47,501] - ==> [2018-05-13 10:08:47 499] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 10:08:47,657] - TCPPacketReceiver::processPendingEvents(10.139.100.106:10176): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 10:08:47,658] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 10:08:47,659] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 10:08:47,660] - onLoginAppShutDown()
  INFO root [2018-05-13 10:08:47,660] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 10:08:47,660] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 10:08:47,661] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 10:08:47,661] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 10:08:47,662] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 10:08:47,662] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 10:08:47,662] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 10:08:47,662] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 10:08:47,662] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 10:08:47,663] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 10:08:47,677] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 10:08:47,677] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-05-13 10:08:47,979] - ThreadPool::destroy(): waiting for thread(2)[0x39f09e0,0x39f06a0,], try=1
  INFO root [2018-05-13 10:08:51,817] - 
  INFO root [2018-05-13 10:08:51,818] - -----------------------------------------------------------------------------------------


  INFO root [2018-05-13 10:08:51,820] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2018-05-13 10:08:51,820] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/assets_Battle of Gods/;D:/kbengine/assets_Battle of Gods/scripts/;D:/kbengine/assets_Battle of Gods/res/
  INFO root [2018-05-13 10:08:51,820] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2018-05-13 10:08:51,827] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:20013 )
  INFO root [2018-05-13 10:08:51,828] - NetworkInterface::initialize(EXTERNAL): address 10.139.100.106:20013, SOMAXCONN=128.
  INFO root [2018-05-13 10:08:51,833] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.100.106 ( 10.139.100.106:10423 )
  INFO root [2018-05-13 10:08:51,833] - NetworkInterface::initialize(INTERNAL): address 10.139.100.106:10423, SOMAXCONN=128.
  INFO root [2018-05-13 10:08:51,834] - server-configs:
  INFO root [2018-05-13 10:08:51,834] - 	internalAddr : 10.139.100.106:10423
  INFO root [2018-05-13 10:08:51,834] - 	externalAddr : 10.139.100.106:20013
  INFO root [2018-05-13 10:08:51,834] - 	componentID : 9000
  INFO root [2018-05-13 10:08:52,111] - Components::findLogger: found logger, addr:10.139.100.106:10403
  INFO root [2018-05-13 10:08:52,111] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2018-05-13 10:08:52,112] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-05-13 10:08:57,527] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: B20F257E332779D9E1EA7D34638E6146. Config: Debug X86. Built: 16:27:30 Apr 30 2018. AppID: 9000. UID: 10103. PID: 15148 ----
  INFO root [2018-05-13 10:08:57,529] - Server : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz with 2097151kB RAM
  INFO root [2018-05-13 10:08:57,530] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-05-13 10:08:57,531] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-05-13 10:08:57,756] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 10:08:57,758] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 10:08:57,759] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 10:08:57,770] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 10:08:57,771] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 10:08:57,772] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 10:08:57,774] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 10:08:57,849] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 10:08:57,898] - Script::install(): is successfully, Python=(3.4.2 (default, Apr 30 2018, 16:27:27) [MSC v.1900 32 bit (Intel)])!
  INFO root [2018-05-13 10:08:57,898] - Script::install(): KBExtra is successfully!
S_INFO root [2018-05-13 10:08:57,903] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-05-13 10:08:57,903] - TelnetServer server is running on port 31000
  INFO root [2018-05-13 10:08:58,539] - ---- loginapp is running ----
 DEBUG root [2018-05-13 10:08:58,539] - Components::process(): Request for the process of identity...
  WARN root [2018-05-13 10:09:04,905] - Forwarding logs to logger[10.139.100.106:10403/0/0/0]...
 ERROR root [2018-05-13 13:04:50,455] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 13:04:50,517] - The following logs sent to logger failed:
  WARN root [2018-05-13 13:04:50,580] - ==> [2018-05-13 13:04:50 462] TCPPacketReceiver::processPendingEvents(10.139.100.106:10403): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 13:04:50,580] - ==> [2018-05-13 13:04:50 465] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-05-13 13:04:50,595] - TCPPacketReceiver::processPendingEvents(10.139.100.106:10406): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-05-13 13:04:50,595] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-05-13 13:04:50,674] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-05-13 13:04:50,705] - onLoginAppShutDown()
  INFO root [2018-05-13 13:04:50,705] - Shutdowner::onShutdown: shutting down
  INFO root [2018-05-13 13:04:50,705] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-05-13 13:04:50,767] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-05-13 13:04:50,924] - Script::uninstall(): is successfully!
 DEBUG root [2018-05-13 13:04:50,924] - ThreadPool::destroy(): starting size 2.
