  INFO root [2018-08-09 09:19:20,270] - 
  INFO root [2018-08-09 09:19:20,270] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:19:20,270] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:19:20,270] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:19:20,270] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:19:20,270] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:19:20,270] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:19:20,286] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2163 )
  INFO root [2018-08-09 09:19:20,286] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2163, SOMAXCONN=128.
  INFO root [2018-08-09 09:19:20,286] - server-configs:
  INFO root [2018-08-09 09:19:20,286] - 	internalAddr : 10.139.89.70:2163
  INFO root [2018-08-09 09:19:20,286] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:19:20,286] - 	componentID : 9000
  INFO root [2018-08-09 09:19:20,629] - Components::findLogger: found logger, addr:10.139.89.70:2149
  INFO root [2018-08-09 09:19:20,629] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:19:20,629] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:19:20,629] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 11936 ----
  INFO root [2018-08-09 09:19:20,629] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:19:20,629] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:19:20,629] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:19:20,770] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:19:20,817] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:19:20,859] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:19:20,859] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:19:20,859] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:19:20,859] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:19:21,155] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:19:21,156] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:19:27,540] - Forwarding logs to logger[10.139.89.70:2149/0/0/0]...
 ERROR root [2018-08-09 09:19:54,457] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:19:54,457] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:19:54,457] - ==> [2018-08-09 09:19:54 458] TCPPacketReceiver::processPendingEvents(10.139.89.70:2149): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:19:54,457] - ==> [2018-08-09 09:19:54 461] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:19:57,301] - 
  INFO root [2018-08-09 09:19:57,301] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:19:57,301] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:19:57,301] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:19:57,301] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:19:57,332] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:19:57,332] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:19:57,332] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2236 )
  INFO root [2018-08-09 09:19:57,332] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2236, SOMAXCONN=128.
  INFO root [2018-08-09 09:19:57,332] - server-configs:
  INFO root [2018-08-09 09:19:57,332] - 	internalAddr : 10.139.89.70:2236
  INFO root [2018-08-09 09:19:57,332] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:19:57,332] - 	componentID : 9000
  INFO root [2018-08-09 09:19:57,862] - Components::findLogger: found logger, addr:10.139.89.70:2230
  INFO root [2018-08-09 09:19:57,862] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:19:57,862] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:19:57,862] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13724 ----
  INFO root [2018-08-09 09:19:57,862] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:19:57,877] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:19:57,877] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:19:58,018] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:19:58,018] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:19:58,018] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:19:58,034] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:19:58,034] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:19:58,034] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:19:58,034] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:19:58,081] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:19:58,126] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:19:58,126] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:19:58,141] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:19:58,141] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:19:58,567] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:19:58,567] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:20:04,884] - Forwarding logs to logger[10.139.89.70:2230/0/0/0]...
 ERROR root [2018-08-09 09:21:16,206] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:21:16,206] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:21:16,206] - ==> [2018-08-09 09:21:16 209] TCPPacketReceiver::processPendingEvents(10.139.89.70:2230): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:21:16,206] - ==> [2018-08-09 09:21:16 210] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:21:16,253] - Components::findComponents: find dbmgr(35)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-08-09 09:21:19,638] - 
  INFO root [2018-08-09 09:21:19,670] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:21:19,670] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:21:19,670] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:21:19,670] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:21:19,717] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:21:19,717] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:21:19,717] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2321 )
  INFO root [2018-08-09 09:21:19,717] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2321, SOMAXCONN=128.
  INFO root [2018-08-09 09:21:19,717] - server-configs:
  INFO root [2018-08-09 09:21:19,717] - 	internalAddr : 10.139.89.70:2321
  INFO root [2018-08-09 09:21:19,717] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:21:19,717] - 	componentID : 9000
  INFO root [2018-08-09 09:21:20,325] - Components::findLogger: found logger, addr:10.139.89.70:2315
  INFO root [2018-08-09 09:21:20,325] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:21:20,325] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:21:20,338] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 5880 ----
  INFO root [2018-08-09 09:21:20,338] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:21:20,339] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:21:20,339] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:21:20,473] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:21:20,520] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:21:20,567] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:21:20,567] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:21:20,567] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:21:20,567] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:21:21,048] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:21:21,048] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:21:27,363] - Forwarding logs to logger[10.139.89.70:2315/0/0/0]...
 ERROR root [2018-08-09 09:22:54,238] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:22:54,238] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:22:54,238] - ==> [2018-08-09 09:22:54 239] TCPPacketReceiver::processPendingEvents(10.139.89.70:2315): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:22:54,238] - ==> [2018-08-09 09:22:54 240] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:22:57,113] - 
  INFO root [2018-08-09 09:22:57,113] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:22:57,113] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:22:57,113] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:22:57,113] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:22:57,145] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:22:57,145] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:22:57,160] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2351 )
  INFO root [2018-08-09 09:22:57,160] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2351, SOMAXCONN=128.
  INFO root [2018-08-09 09:22:57,160] - server-configs:
  INFO root [2018-08-09 09:22:57,160] - 	internalAddr : 10.139.89.70:2351
  INFO root [2018-08-09 09:22:57,160] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:22:57,160] - 	componentID : 9000
  INFO root [2018-08-09 09:22:57,857] - Components::findLogger: found logger, addr:10.139.89.70:2346
  INFO root [2018-08-09 09:22:57,857] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:22:57,857] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:22:57,857] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13456 ----
  INFO root [2018-08-09 09:22:57,857] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:22:57,857] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:22:57,857] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:22:57,998] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:22:58,029] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:22:58,081] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:22:58,081] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:22:58,084] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:22:58,084] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:22:58,560] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:22:58,576] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:23:04,894] - Forwarding logs to logger[10.139.89.70:2346/0/0/0]...
 ERROR root [2018-08-09 09:24:42,990] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:24:43,006] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:24:43,006] - ==> [2018-08-09 09:24:43 000] TCPPacketReceiver::processPendingEvents(10.139.89.70:2346): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:24:43,006] - ==> [2018-08-09 09:24:43 005] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:24:43,092] - Components::findComponents: find dbmgr(48)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-08-09 09:24:46,516] - 
  INFO root [2018-08-09 09:24:46,517] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:24:46,518] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:24:46,518] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:24:46,519] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:24:46,548] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:24:46,548] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:24:46,553] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2375 )
  INFO root [2018-08-09 09:24:46,553] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2375, SOMAXCONN=128.
  INFO root [2018-08-09 09:24:46,553] - server-configs:
  INFO root [2018-08-09 09:24:46,553] - 	internalAddr : 10.139.89.70:2375
  INFO root [2018-08-09 09:24:46,553] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:24:46,554] - 	componentID : 9000
  INFO root [2018-08-09 09:24:47,229] - Components::findLogger: found logger, addr:10.139.89.70:2368
  INFO root [2018-08-09 09:24:47,229] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:24:47,229] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:24:47,235] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 12708 ----
  INFO root [2018-08-09 09:24:47,235] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:24:47,235] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:24:47,235] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:24:47,372] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:24:47,372] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:24:47,372] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:24:47,372] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:24:47,388] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:24:47,388] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:24:47,388] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:24:47,419] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:24:47,450] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:24:47,450] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:24:47,450] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:24:47,450] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:24:47,856] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:24:47,856] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:24:54,108] - Forwarding logs to logger[10.139.89.70:2368/0/0/0]...
 ERROR root [2018-08-09 09:26:16,363] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:26:16,363] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:26:16,363] - ==> [2018-08-09 09:26:16 364] TCPPacketReceiver::processPendingEvents(10.139.89.70:2368): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:26:16,363] - ==> [2018-08-09 09:26:16 365] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:26:19,538] - 
  INFO root [2018-08-09 09:26:19,585] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:26:19,585] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:26:19,585] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:26:19,585] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:26:19,663] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:26:19,663] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:26:19,678] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2422 )
  INFO root [2018-08-09 09:26:19,678] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2422, SOMAXCONN=128.
  INFO root [2018-08-09 09:26:19,678] - server-configs:
  INFO root [2018-08-09 09:26:19,678] - 	internalAddr : 10.139.89.70:2422
  INFO root [2018-08-09 09:26:19,678] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:26:19,678] - 	componentID : 9000
  INFO root [2018-08-09 09:26:20,301] - Components::findLogger: found logger, addr:10.139.89.70:2416
  INFO root [2018-08-09 09:26:20,301] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:26:20,301] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:26:20,316] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 5792 ----
  INFO root [2018-08-09 09:26:20,316] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:26:20,316] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:26:20,316] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:26:20,457] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:26:20,504] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:26:20,535] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:26:20,535] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:26:20,535] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:26:20,535] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:26:21,032] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:26:21,032] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:26:27,333] - Forwarding logs to logger[10.139.89.70:2416/0/0/0]...
 ERROR root [2018-08-09 09:27:17,702] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:27:17,702] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:27:17,702] - ==> [2018-08-09 09:27:17 701] TCPPacketReceiver::processPendingEvents(10.139.89.70:2416): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:27:17,702] - ==> [2018-08-09 09:27:17 702] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:27:17,983] - Components::findComponents: find dbmgr(25)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-08-09 09:29:15,513] - 
  INFO root [2018-08-09 09:29:15,513] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:29:15,513] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:29:15,513] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:29:15,513] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:29:15,544] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:29:15,544] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:29:15,560] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2445 )
  INFO root [2018-08-09 09:29:15,560] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2445, SOMAXCONN=128.
  INFO root [2018-08-09 09:29:15,560] - server-configs:
  INFO root [2018-08-09 09:29:15,560] - 	internalAddr : 10.139.89.70:2445
  INFO root [2018-08-09 09:29:15,560] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:29:15,560] - 	componentID : 9000
  INFO root [2018-08-09 09:29:16,109] - Components::findLogger: found logger, addr:10.139.89.70:2439
  INFO root [2018-08-09 09:29:16,109] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:29:16,109] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:29:16,117] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 5280 ----
  INFO root [2018-08-09 09:29:16,119] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:29:16,119] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:29:16,119] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:29:16,253] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:29:16,300] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:29:16,362] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:29:16,362] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:29:16,362] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:29:16,362] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:29:16,706] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:29:16,706] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:29:22,964] - Forwarding logs to logger[10.139.89.70:2439/0/0/0]...
 ERROR root [2018-08-09 09:29:23,397] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:29:23,397] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:29:23,397] - ==> [2018-08-09 09:29:23 403] TCPPacketReceiver::processPendingEvents(10.139.89.70:2439): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:29:23,397] - ==> [2018-08-09 09:29:23 404] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:29:23,991] - Components::findComponents: find dbmgr(1)...
  INFO root [2018-08-09 09:43:33,707] - 
  INFO root [2018-08-09 09:43:33,723] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:43:33,723] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:43:33,723] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:43:33,723] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:43:33,848] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:43:33,848] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:43:33,879] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2803 )
  INFO root [2018-08-09 09:43:33,879] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2803, SOMAXCONN=128.
  INFO root [2018-08-09 09:43:33,879] - server-configs:
  INFO root [2018-08-09 09:43:33,879] - 	internalAddr : 10.139.89.70:2803
  INFO root [2018-08-09 09:43:33,879] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:43:33,879] - 	componentID : 9000
  INFO root [2018-08-09 09:43:34,563] - Components::findLogger: found logger, addr:10.139.89.70:2797
  INFO root [2018-08-09 09:43:34,563] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:43:34,563] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:43:34,563] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 5084 ----
  INFO root [2018-08-09 09:43:34,563] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:43:34,563] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:43:34,563] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:43:34,704] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:43:34,704] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:43:34,704] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:43:34,719] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:43:34,719] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:43:34,719] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:43:34,719] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:43:34,750] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:43:34,797] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:43:34,797] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:43:34,797] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:43:34,797] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:43:35,314] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:43:35,314] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:43:41,597] - Forwarding logs to logger[10.139.89.70:2797/0/0/0]...
 ERROR root [2018-08-09 09:45:09,410] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:45:09,410] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:45:09,410] - ==> [2018-08-09 09:45:09 411] TCPPacketReceiver::processPendingEvents(10.139.89.70:2797): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:45:09,410] - ==> [2018-08-09 09:45:09 417] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:45:09,567] - TCPPacketReceiver::processPendingEvents(10.139.89.70:2798): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:45:09,582] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:45:09,582] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 09:45:09,582] - onLoginAppShutDown()
  INFO root [2018-08-09 09:45:09,582] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 09:45:09,582] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:45:09,582] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:45:09,613] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 09:45:09,613] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 09:45:09,933] - ThreadPool::destroy(): waiting for thread(2)[0xe98a8,0xe8d48,], try=1
  INFO root [2018-08-09 09:45:12,925] - 
  INFO root [2018-08-09 09:45:12,956] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:45:12,956] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:45:12,956] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:45:12,956] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:45:13,019] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:45:13,019] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:45:13,034] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2842 )
  INFO root [2018-08-09 09:45:13,034] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2842, SOMAXCONN=128.
  INFO root [2018-08-09 09:45:13,034] - server-configs:
  INFO root [2018-08-09 09:45:13,034] - 	internalAddr : 10.139.89.70:2842
  INFO root [2018-08-09 09:45:13,034] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:45:13,034] - 	componentID : 9000
  INFO root [2018-08-09 09:45:13,534] - Components::findLogger: found logger, addr:10.139.89.70:2835
  INFO root [2018-08-09 09:45:13,534] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:45:13,534] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:45:13,534] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 12700 ----
  INFO root [2018-08-09 09:45:13,534] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:45:13,534] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:45:13,534] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:45:13,691] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:45:13,737] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:45:13,784] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:45:13,785] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:45:13,787] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:45:13,787] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:45:14,513] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:45:14,560] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:45:20,847] - Forwarding logs to logger[10.139.89.70:2835/0/0/0]...
 ERROR root [2018-08-09 09:48:50,662] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:48:50,664] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:48:50,664] - ==> [2018-08-09 09:48:50 660] TCPPacketReceiver::processPendingEvents(10.139.89.70:2835): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:48:50,664] - ==> [2018-08-09 09:48:50 664] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:48:50,834] - TCPPacketReceiver::processPendingEvents(10.139.89.70:2837): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:48:50,849] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:48:50,851] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 09:48:50,866] - onLoginAppShutDown()
  INFO root [2018-08-09 09:48:50,867] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 09:48:50,867] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 09:48:50,868] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:48:50,868] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:48:50,868] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:48:50,868] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:48:50,869] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:48:50,869] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:48:50,869] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:48:50,869] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:48:50,902] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 09:48:50,902] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 09:48:51,204] - ThreadPool::destroy(): waiting for thread(2)[0xe89b0,0xe8e90,], try=1
 DEBUG root [2018-08-09 09:48:51,636] - TPThread::~TPThread(): 0xe89b0
 DEBUG root [2018-08-09 09:48:51,636] - TPThread::~TPThread(): 0xe8e90
 DEBUG root [2018-08-09 09:48:51,636] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 09:48:51,645] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 09:48:51,645] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 09:48:51,645] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 09:48:51,645] - UDPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-08-09 09:48:51,645] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 09:48:51,645] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 09:48:51,645] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 09:48:51,645] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 09:48:51,645] - loginapp(9000) has shut down.
  INFO root [2018-08-09 09:48:54,179] - 
  INFO root [2018-08-09 09:48:54,206] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 09:48:54,207] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 09:48:54,208] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 09:48:54,208] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 09:48:54,261] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 09:48:54,261] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 09:48:54,267] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:3009 )
  INFO root [2018-08-09 09:48:54,267] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:3009, SOMAXCONN=128.
  INFO root [2018-08-09 09:48:54,268] - server-configs:
  INFO root [2018-08-09 09:48:54,268] - 	internalAddr : 10.139.89.70:3009
  INFO root [2018-08-09 09:48:54,268] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 09:48:54,268] - 	componentID : 9000
  INFO root [2018-08-09 09:48:54,905] - Components::findLogger: found logger, addr:10.139.89.70:3003
  INFO root [2018-08-09 09:48:54,906] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 09:48:54,906] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 09:48:54,914] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 4344 ----
  INFO root [2018-08-09 09:48:54,915] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 09:48:54,916] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 09:48:54,917] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 09:48:55,109] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:48:55,110] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:48:55,110] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:48:55,115] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:48:55,115] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:48:55,115] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:48:55,117] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:48:55,178] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:48:55,239] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 09:48:55,239] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 09:48:55,249] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 09:48:55,249] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 09:48:56,160] - ---- loginapp is running ----
 DEBUG root [2018-08-09 09:48:56,160] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 09:49:02,555] - Forwarding logs to logger[10.139.89.70:3003/0/0/0]...
 ERROR root [2018-08-09 09:51:17,111] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:51:17,113] - The following logs sent to logger failed:
  WARN root [2018-08-09 09:51:17,114] - ==> [2018-08-09 09:51:17 108] TCPPacketReceiver::processPendingEvents(10.139.89.70:3003): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:51:17,114] - ==> [2018-08-09 09:51:17 112] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 09:51:17,259] - TCPPacketReceiver::processPendingEvents(10.139.89.70:3004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 09:51:17,268] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 09:51:17,280] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 09:51:17,280] - onLoginAppShutDown()
  INFO root [2018-08-09 09:51:17,280] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 09:51:17,280] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 09:51:17,280] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 09:51:17,309] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 09:51:17,309] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 09:51:17,615] - ThreadPool::destroy(): waiting for thread(2)[0xba9b08,0xba95c0,], try=1
  INFO root [2018-08-09 10:09:11,884] - 
  INFO root [2018-08-09 10:09:11,887] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:09:11,894] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:09:11,894] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:09:11,894] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:09:11,952] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:09:11,952] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:09:11,959] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:3548 )
  INFO root [2018-08-09 10:09:11,959] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:3548, SOMAXCONN=128.
  INFO root [2018-08-09 10:09:11,959] - server-configs:
  INFO root [2018-08-09 10:09:11,959] - 	internalAddr : 10.139.89.70:3548
  INFO root [2018-08-09 10:09:11,959] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:09:11,962] - 	componentID : 9000
  INFO root [2018-08-09 10:09:12,618] - Components::findLogger: found logger, addr:10.139.89.70:3541
  INFO root [2018-08-09 10:09:12,619] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:09:12,619] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:09:12,627] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 7220 ----
  INFO root [2018-08-09 10:09:12,628] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:09:12,629] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:09:12,629] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:09:12,781] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:09:12,781] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:09:12,781] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:09:12,787] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:09:12,787] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:09:12,787] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:09:12,787] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:09:12,832] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:09:12,868] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:09:12,868] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:09:12,868] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:09:12,868] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:09:13,308] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:09:13,311] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:09:19,687] - Forwarding logs to logger[10.139.89.70:3541/0/0/0]...
 ERROR root [2018-08-09 10:10:27,501] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:10:27,507] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:10:27,507] - ==> [2018-08-09 10:10:27 497] TCPPacketReceiver::processPendingEvents(10.139.89.70:3541): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:10:27,507] - ==> [2018-08-09 10:10:27 505] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:10:27,658] - TCPPacketReceiver::processPendingEvents(10.139.89.70:3542): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:10:27,667] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:10:27,672] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:10:27,672] - onLoginAppShutDown()
  INFO root [2018-08-09 10:10:27,672] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:10:27,672] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:10:27,672] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:10:27,677] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:10:27,699] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:10:27,711] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:10:28,013] - ThreadPool::destroy(): waiting for thread(2)[0xa98c8,0xa9040,], try=1
  INFO root [2018-08-09 10:10:31,590] - 
  INFO root [2018-08-09 10:10:31,590] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:10:31,592] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:10:31,592] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:10:31,592] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:10:31,600] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:10:31,600] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:10:31,602] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:3626 )
  INFO root [2018-08-09 10:10:31,602] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:3626, SOMAXCONN=128.
  INFO root [2018-08-09 10:10:31,602] - server-configs:
  INFO root [2018-08-09 10:10:31,602] - 	internalAddr : 10.139.89.70:3626
  INFO root [2018-08-09 10:10:31,602] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:10:31,602] - 	componentID : 9000
  INFO root [2018-08-09 10:10:32,123] - Components::findLogger: found logger, addr:10.139.89.70:3620
  INFO root [2018-08-09 10:10:32,124] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:10:32,124] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:10:32,136] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 13996 ----
  INFO root [2018-08-09 10:10:32,142] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:10:32,142] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:10:32,142] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:10:32,360] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:10:32,360] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:10:32,360] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:10:32,368] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:10:32,370] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:10:32,370] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:10:32,370] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:10:32,430] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:10:32,511] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:10:32,511] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:10:32,516] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:10:32,516] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:10:33,189] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:10:33,189] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:10:39,557] - Forwarding logs to logger[10.139.89.70:3620/0/0/0]...
 ERROR root [2018-08-09 10:39:25,025] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:39:25,032] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:39:25,032] - ==> [2018-08-09 10:39:25 022] TCPPacketReceiver::processPendingEvents(10.139.89.70:3620): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:39:25,032] - ==> [2018-08-09 10:39:25 027] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:39:25,169] - TCPPacketReceiver::processPendingEvents(10.139.89.70:3621): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:39:25,178] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:39:25,180] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:39:25,180] - onLoginAppShutDown()
  INFO root [2018-08-09 10:39:25,181] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:39:25,181] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:39:25,181] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:39:25,181] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:39:25,182] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:39:25,182] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:39:25,182] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:39:25,182] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:39:25,183] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:39:25,183] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:39:25,212] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:39:25,214] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:39:25,516] - ThreadPool::destroy(): waiting for thread(2)[0xa19558,0xa196f8,], try=1
  INFO root [2018-08-09 10:39:28,779] - 
  INFO root [2018-08-09 10:39:28,784] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:39:28,786] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:39:28,786] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:39:28,786] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:39:28,817] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:39:28,818] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:39:28,842] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:4727 )
  INFO root [2018-08-09 10:39:28,843] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:4727, SOMAXCONN=128.
  INFO root [2018-08-09 10:39:28,843] - server-configs:
  INFO root [2018-08-09 10:39:28,843] - 	internalAddr : 10.139.89.70:4727
  INFO root [2018-08-09 10:39:28,843] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:39:28,843] - 	componentID : 9000
  INFO root [2018-08-09 10:39:29,382] - Components::findLogger: found logger, addr:10.139.89.70:4721
  INFO root [2018-08-09 10:39:29,383] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:39:29,383] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:39:29,389] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14660 ----
  INFO root [2018-08-09 10:39:29,390] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:39:29,390] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:39:29,390] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:39:29,519] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:39:29,519] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:39:29,519] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:39:29,523] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:39:29,523] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:39:29,523] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:39:29,524] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:39:29,558] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:39:29,594] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:39:29,594] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:39:29,596] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:39:29,596] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:39:29,978] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:39:29,978] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:39:36,168] - Forwarding logs to logger[10.139.89.70:4721/0/0/0]...
 ERROR root [2018-08-09 10:40:37,626] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:40:37,629] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:40:37,630] - ==> [2018-08-09 10:40:37 624] TCPPacketReceiver::processPendingEvents(10.139.89.70:4721): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:40:37,630] - ==> [2018-08-09 10:40:37 627] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:40:37,996] - Components::findComponents: find dbmgr(31)...
delay time is too long, please check the dbmgr logs!
  INFO root [2018-08-09 10:40:41,184] - 
  INFO root [2018-08-09 10:40:41,187] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:40:41,188] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:40:41,188] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:40:41,190] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:40:41,198] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:40:41,199] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:40:41,206] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:4772 )
  INFO root [2018-08-09 10:40:41,206] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:4772, SOMAXCONN=128.
  INFO root [2018-08-09 10:40:41,206] - server-configs:
  INFO root [2018-08-09 10:40:41,206] - 	internalAddr : 10.139.89.70:4772
  INFO root [2018-08-09 10:40:41,207] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:40:41,207] - 	componentID : 9000
  INFO root [2018-08-09 10:40:41,764] - Components::findLogger: found logger, addr:10.139.89.70:4766
  INFO root [2018-08-09 10:40:41,764] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:40:41,764] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:40:41,772] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 10156 ----
  INFO root [2018-08-09 10:40:41,772] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:40:41,773] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:40:41,773] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:40:41,911] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:40:41,911] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:40:41,912] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:40:41,915] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:40:41,915] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:40:41,915] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:40:41,916] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:40:41,960] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:40:42,004] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:40:42,005] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:40:42,007] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:40:42,008] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:40:42,514] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:40:42,515] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:40:48,775] - Forwarding logs to logger[10.139.89.70:4766/0/0/0]...
 ERROR root [2018-08-09 10:41:23,684] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:41:23,685] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:41:23,686] - ==> [2018-08-09 10:41:23 680] TCPPacketReceiver::processPendingEvents(10.139.89.70:4766): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:41:23,686] - ==> [2018-08-09 10:41:23 686] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:41:23,825] - TCPPacketReceiver::processPendingEvents(10.139.89.70:4767): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:41:23,835] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:41:23,838] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:41:23,839] - onLoginAppShutDown()
  INFO root [2018-08-09 10:41:23,839] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:41:23,839] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:41:23,840] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:41:23,841] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:41:23,842] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:41:23,842] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:41:23,842] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:41:23,842] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:41:23,842] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:41:23,843] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:41:23,872] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:41:23,872] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:41:24,174] - ThreadPool::destroy(): waiting for thread(2)[0x218520,0x218ad0,], try=1
  INFO root [2018-08-09 10:41:27,071] - 
  INFO root [2018-08-09 10:41:27,079] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:41:27,081] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:41:27,081] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:41:27,081] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:41:27,101] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:41:27,102] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:41:27,106] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:4818 )
  INFO root [2018-08-09 10:41:27,107] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:4818, SOMAXCONN=128.
  INFO root [2018-08-09 10:41:27,107] - server-configs:
  INFO root [2018-08-09 10:41:27,107] - 	internalAddr : 10.139.89.70:4818
  INFO root [2018-08-09 10:41:27,107] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:41:27,107] - 	componentID : 9000
  INFO root [2018-08-09 10:41:27,791] - Components::findLogger: found logger, addr:10.139.89.70:4813
  INFO root [2018-08-09 10:41:27,791] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:41:27,791] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:41:27,796] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 4968 ----
  INFO root [2018-08-09 10:41:27,797] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:41:27,797] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:41:27,797] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:41:27,942] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:41:27,943] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:41:27,944] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:41:27,948] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:41:27,948] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:41:27,948] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:41:27,949] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:41:27,994] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:41:28,037] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:41:28,038] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:41:28,040] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:41:28,040] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:41:28,590] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:41:28,591] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:41:34,796] - Forwarding logs to logger[10.139.89.70:4813/0/0/0]...
 ERROR root [2018-08-09 10:42:50,042] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:42:50,046] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:42:50,046] - ==> [2018-08-09 10:42:50 041] TCPPacketReceiver::processPendingEvents(10.139.89.70:4813): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:42:50,046] - ==> [2018-08-09 10:42:50 043] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:42:50,179] - TCPPacketReceiver::processPendingEvents(10.139.89.70:4814): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:42:50,193] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:42:50,195] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:42:50,198] - onLoginAppShutDown()
  INFO root [2018-08-09 10:42:50,199] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:42:50,199] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:42:50,200] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:42:50,201] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:42:50,201] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:42:50,202] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:42:50,202] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:42:50,203] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:42:50,204] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:42:50,205] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:42:50,242] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:42:50,242] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:42:50,544] - ThreadPool::destroy(): waiting for thread(2)[0xda9cd8,0xda9040,], try=1
  INFO root [2018-08-09 10:42:53,669] - 
  INFO root [2018-08-09 10:42:53,670] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:42:53,674] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:42:53,675] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:42:53,675] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:42:53,690] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:42:53,690] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:42:53,696] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:4880 )
  INFO root [2018-08-09 10:42:53,696] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:4880, SOMAXCONN=128.
  INFO root [2018-08-09 10:42:53,697] - server-configs:
  INFO root [2018-08-09 10:42:53,697] - 	internalAddr : 10.139.89.70:4880
  INFO root [2018-08-09 10:42:53,697] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:42:53,697] - 	componentID : 9000
  INFO root [2018-08-09 10:42:54,237] - Components::findLogger: found logger, addr:10.139.89.70:4873
  INFO root [2018-08-09 10:42:54,237] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:42:54,237] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:42:54,245] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 11460 ----
  INFO root [2018-08-09 10:42:54,245] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:42:54,247] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:42:54,247] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:42:54,383] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:42:54,384] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:42:54,384] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:42:54,388] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:42:54,388] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:42:54,389] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:42:54,389] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:42:54,431] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:42:54,505] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:42:54,506] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:42:54,508] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:42:54,508] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:42:55,169] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:42:55,178] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:43:01,572] - Forwarding logs to logger[10.139.89.70:4873/0/0/0]...
 ERROR root [2018-08-09 10:43:47,271] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:43:47,272] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:43:47,272] - ==> [2018-08-09 10:43:47 271] TCPPacketReceiver::processPendingEvents(10.139.89.70:4873): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:43:47,273] - ==> [2018-08-09 10:43:47 272] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:43:47,421] - TCPPacketReceiver::processPendingEvents(10.139.89.70:4872): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:43:47,429] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:43:47,439] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:43:47,439] - onLoginAppShutDown()
  INFO root [2018-08-09 10:43:47,439] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:43:47,440] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:43:47,440] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:43:47,440] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:43:47,441] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:43:47,441] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:43:47,441] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:43:47,442] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:43:47,442] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:43:47,442] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:43:47,474] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:43:47,475] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:43:47,777] - ThreadPool::destroy(): waiting for thread(2)[0x99d1e8,0x99d320,], try=1
  INFO root [2018-08-09 10:47:36,504] - 
  INFO root [2018-08-09 10:47:36,519] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:47:36,520] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:47:36,521] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:47:36,521] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:47:36,568] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:47:36,568] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:47:36,580] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5161 )
  INFO root [2018-08-09 10:47:36,580] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5161, SOMAXCONN=128.
  INFO root [2018-08-09 10:47:36,580] - server-configs:
  INFO root [2018-08-09 10:47:36,580] - 	internalAddr : 10.139.89.70:5161
  INFO root [2018-08-09 10:47:36,581] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:47:36,581] - 	componentID : 9000
  INFO root [2018-08-09 10:47:38,633] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 15468 ----
  INFO root [2018-08-09 10:47:38,633] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:47:38,633] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:47:38,634] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:47:38,763] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:47:38,764] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:47:38,764] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:47:38,767] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:47:38,768] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:47:38,768] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:47:38,768] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:47:38,802] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:47:38,836] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:47:38,836] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:47:38,839] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:47:38,839] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:47:39,198] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:47:39,198] - Components::process(): Request for the process of identity...
  INFO root [2018-08-09 10:47:46,379] - Components::findComponents: find logger(1)...
  INFO root [2018-08-09 10:47:46,418] - Components::findComponents: found logger, addr:10.139.89.70:5154
  INFO root [2018-08-09 10:47:46,419] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:47:46,419] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:47:46,422] - Components::findComponents: find dbmgr(2)...
  WARN root [2018-08-09 10:47:47,525] - Forwarding logs to logger[10.139.89.70:5154/0/0/0]...
 ERROR root [2018-08-09 10:48:00,315] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:48:00,319] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:48:00,320] - ==> [2018-08-09 10:48:00 311] TCPPacketReceiver::processPendingEvents(10.139.89.70:5154): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:48:00,320] - ==> [2018-08-09 10:48:00 316] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:48:00,739] - Components::findComponents: find dbmgr(9)...
  INFO root [2018-08-09 10:48:03,523] - 
  INFO root [2018-08-09 10:48:03,525] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:48:03,527] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:48:03,527] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:48:03,527] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:48:03,559] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:48:03,560] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:48:03,583] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5205 )
  INFO root [2018-08-09 10:48:03,583] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5205, SOMAXCONN=128.
  INFO root [2018-08-09 10:48:03,583] - server-configs:
  INFO root [2018-08-09 10:48:03,583] - 	internalAddr : 10.139.89.70:5205
  INFO root [2018-08-09 10:48:03,583] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:48:03,583] - 	componentID : 9000
  INFO root [2018-08-09 10:48:04,207] - Components::findLogger: found logger, addr:10.139.89.70:5199
  INFO root [2018-08-09 10:48:04,208] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:48:04,208] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:48:04,219] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14764 ----
  INFO root [2018-08-09 10:48:04,219] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:48:04,220] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:48:04,220] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:48:04,371] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:48:04,371] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:48:04,373] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:48:04,379] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:48:04,381] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:48:04,382] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:48:04,383] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:48:04,453] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:48:04,536] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:48:04,536] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:48:04,540] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:48:04,540] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:48:05,082] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:48:05,083] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:48:11,289] - Forwarding logs to logger[10.139.89.70:5199/0/0/0]...
 ERROR root [2018-08-09 10:48:51,829] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:48:51,831] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:48:51,831] - ==> [2018-08-09 10:48:51 829] TCPPacketReceiver::processPendingEvents(10.139.89.70:5199): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:48:51,831] - ==> [2018-08-09 10:48:51 830] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:50:23,504] - 
  INFO root [2018-08-09 10:50:23,504] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:50:23,506] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:50:23,506] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:50:23,506] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:50:23,522] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:50:23,524] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:50:23,534] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5415 )
  INFO root [2018-08-09 10:50:23,535] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5415, SOMAXCONN=128.
  INFO root [2018-08-09 10:50:23,535] - server-configs:
  INFO root [2018-08-09 10:50:23,535] - 	internalAddr : 10.139.89.70:5415
  INFO root [2018-08-09 10:50:23,535] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:50:23,536] - 	componentID : 9000
  INFO root [2018-08-09 10:50:24,138] - Components::findLogger: found logger, addr:10.139.89.70:5407
  INFO root [2018-08-09 10:50:24,138] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:50:24,139] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:50:24,146] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 3968 ----
  INFO root [2018-08-09 10:50:24,147] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:50:24,147] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:50:24,148] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:50:24,291] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:50:24,292] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:50:24,293] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:50:24,298] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:50:24,299] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:50:24,299] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:50:24,300] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:50:24,358] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:50:24,425] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:50:24,425] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:50:24,429] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:50:24,430] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:50:25,134] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:50:25,135] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:50:31,374] - Forwarding logs to logger[10.139.89.70:5407/0/0/0]...
 ERROR root [2018-08-09 10:53:08,329] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:53:08,335] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:53:08,335] - ==> [2018-08-09 10:53:08 330] TCPPacketReceiver::processPendingEvents(10.139.89.70:5407): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:53:08,335] - ==> [2018-08-09 10:53:08 331] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:53:08,483] - TCPPacketReceiver::processPendingEvents(10.139.89.70:5408): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:53:08,489] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:53:08,494] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:53:08,496] - onLoginAppShutDown()
  INFO root [2018-08-09 10:53:08,496] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:53:08,496] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:53:08,497] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:53:08,497] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:53:08,497] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:53:08,497] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:53:08,497] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:53:08,498] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:53:08,498] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:53:08,498] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:53:08,532] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:53:08,532] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:53:08,833] - ThreadPool::destroy(): waiting for thread(2)[0x9f90b0,0x9f9180,], try=1
  INFO root [2018-08-09 10:53:11,851] - 
  INFO root [2018-08-09 10:53:11,852] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:53:11,854] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:53:11,854] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:53:11,854] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:53:11,892] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:53:11,892] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:53:11,917] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5708 )
  INFO root [2018-08-09 10:53:11,917] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5708, SOMAXCONN=128.
  INFO root [2018-08-09 10:53:11,917] - server-configs:
  INFO root [2018-08-09 10:53:11,917] - 	internalAddr : 10.139.89.70:5708
  INFO root [2018-08-09 10:53:11,917] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:53:11,918] - 	componentID : 9000
  INFO root [2018-08-09 10:53:12,675] - Components::findLogger: found logger, addr:10.139.89.70:5700
  INFO root [2018-08-09 10:53:12,675] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:53:12,675] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:53:12,684] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14616 ----
  INFO root [2018-08-09 10:53:12,684] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:53:12,685] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:53:12,686] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:53:12,850] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:53:12,851] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:53:12,852] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:53:12,860] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:53:12,860] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:53:12,861] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:53:12,862] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:53:12,925] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:53:13,004] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:53:13,004] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:53:13,013] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:53:13,021] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:53:13,552] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:53:13,553] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:53:19,751] - Forwarding logs to logger[10.139.89.70:5700/0/0/0]...
 ERROR root [2018-08-09 10:54:21,327] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:54:21,329] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:54:21,329] - ==> [2018-08-09 10:54:21 319] TCPPacketReceiver::processPendingEvents(10.139.89.70:5700): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:54:21,329] - ==> [2018-08-09 10:54:21 327] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:54:21,498] - TCPPacketReceiver::processPendingEvents(10.139.89.70:5701): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:54:21,530] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:54:21,558] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:54:21,560] - onLoginAppShutDown()
  INFO root [2018-08-09 10:54:21,560] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:54:21,560] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:54:21,561] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:54:21,561] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:54:21,561] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:54:21,561] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:54:21,561] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:54:21,562] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:54:21,562] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:54:21,562] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:54:21,595] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:54:21,596] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:54:21,896] - ThreadPool::destroy(): waiting for thread(2)[0xd48b30,0xd48c68,], try=1
  INFO root [2018-08-09 10:54:24,632] - 
  INFO root [2018-08-09 10:54:24,655] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:54:24,657] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:54:24,657] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:54:24,657] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:54:24,750] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:54:24,751] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:54:24,774] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5855 )
  INFO root [2018-08-09 10:54:24,775] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5855, SOMAXCONN=128.
  INFO root [2018-08-09 10:54:24,775] - server-configs:
  INFO root [2018-08-09 10:54:24,775] - 	internalAddr : 10.139.89.70:5855
  INFO root [2018-08-09 10:54:24,775] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:54:24,775] - 	componentID : 9000
  INFO root [2018-08-09 10:54:25,332] - Components::findLogger: found logger, addr:10.139.89.70:5851
  INFO root [2018-08-09 10:54:25,333] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:54:25,333] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:54:25,344] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14868 ----
  INFO root [2018-08-09 10:54:25,345] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:54:25,345] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:54:25,346] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:54:25,500] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:54:25,501] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:54:25,501] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:54:25,507] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:54:25,508] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:54:25,508] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:54:25,509] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:54:25,561] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:54:25,609] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:54:25,610] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:54:25,615] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:54:25,615] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:54:26,317] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:54:26,319] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:54:32,671] - Forwarding logs to logger[10.139.89.70:5851/0/0/0]...
 ERROR root [2018-08-09 10:54:41,652] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:54:41,655] - The following logs sent to logger failed:
  WARN root [2018-08-09 10:54:41,657] - ==> [2018-08-09 10:54:41 648] TCPPacketReceiver::processPendingEvents(10.139.89.70:5851): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:54:41,658] - ==> [2018-08-09 10:54:41 654] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 10:54:41,812] - TCPPacketReceiver::processPendingEvents(10.139.89.70:5848): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 10:54:41,821] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 10:54:41,829] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 10:54:41,832] - onLoginAppShutDown()
  INFO root [2018-08-09 10:54:41,834] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 10:54:41,835] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 10:54:41,837] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:54:41,838] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:54:41,838] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:54:41,839] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:54:41,839] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:54:41,839] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:54:41,839] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:54:41,839] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:54:41,873] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 10:54:41,874] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 10:54:42,176] - ThreadPool::destroy(): waiting for thread(2)[0x8f9c00,0x8f95e8,], try=1
 DEBUG root [2018-08-09 10:54:42,578] - TPThread::~TPThread(): 0x8f9c00
 DEBUG root [2018-08-09 10:54:42,578] - TPThread::~TPThread(): 0x8f95e8
 DEBUG root [2018-08-09 10:54:42,578] - ThreadPool::destroy(): successfully!
  INFO root [2018-08-09 10:55:20,113] - 
  INFO root [2018-08-09 10:55:20,128] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 10:55:20,130] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 10:55:20,130] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 10:55:20,130] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 10:55:20,219] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 10:55:20,220] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 10:55:20,249] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:5927 )
  INFO root [2018-08-09 10:55:20,249] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:5927, SOMAXCONN=128.
  INFO root [2018-08-09 10:55:20,249] - server-configs:
  INFO root [2018-08-09 10:55:20,250] - 	internalAddr : 10.139.89.70:5927
  INFO root [2018-08-09 10:55:20,250] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 10:55:20,250] - 	componentID : 9000
  INFO root [2018-08-09 10:55:20,927] - Components::findLogger: found logger, addr:10.139.89.70:5921
  INFO root [2018-08-09 10:55:20,927] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 10:55:20,927] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 10:55:20,936] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14340 ----
  INFO root [2018-08-09 10:55:20,936] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 10:55:20,937] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 10:55:20,937] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 10:55:21,078] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 10:55:21,079] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 10:55:21,080] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 10:55:21,085] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 10:55:21,086] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 10:55:21,086] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 10:55:21,087] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 10:55:21,134] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 10:55:21,172] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 10:55:21,173] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 10:55:21,176] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 10:55:21,177] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 10:55:21,883] - ---- loginapp is running ----
 DEBUG root [2018-08-09 10:55:21,891] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 10:55:28,233] - Forwarding logs to logger[10.139.89.70:5921/0/0/0]...
 ERROR root [2018-08-09 11:00:57,962] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 11:00:57,966] - The following logs sent to logger failed:
  WARN root [2018-08-09 11:00:57,966] - ==> [2018-08-09 11:00:57 956] TCPPacketReceiver::processPendingEvents(10.139.89.70:5921): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 11:00:57,966] - ==> [2018-08-09 11:00:57 963] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 11:00:58,142] - TCPPacketReceiver::processPendingEvents(10.139.89.70:5922): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 11:00:58,148] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 11:00:58,150] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 11:00:58,151] - onLoginAppShutDown()
  INFO root [2018-08-09 11:00:58,151] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 11:00:58,151] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 11:00:58,151] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 11:00:58,152] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 11:00:58,152] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 11:00:58,152] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 11:00:58,153] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 11:00:58,153] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 11:00:58,154] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 11:00:58,155] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 11:00:58,195] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 11:00:58,195] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 11:00:58,497] - ThreadPool::destroy(): waiting for thread(2)[0x238e50,0x238f88,], try=1
  INFO root [2018-08-09 11:01:01,765] - 
  INFO root [2018-08-09 11:01:01,791] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 11:01:01,802] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 11:01:01,803] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 11:01:01,803] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 11:01:01,947] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 11:01:01,948] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 11:01:01,954] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:6175 )
  INFO root [2018-08-09 11:01:01,955] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:6175, SOMAXCONN=128.
  INFO root [2018-08-09 11:01:01,955] - server-configs:
  INFO root [2018-08-09 11:01:01,955] - 	internalAddr : 10.139.89.70:6175
  INFO root [2018-08-09 11:01:01,955] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 11:01:01,955] - 	componentID : 9000
  INFO root [2018-08-09 11:01:02,628] - Components::findLogger: found logger, addr:10.139.89.70:6168
  INFO root [2018-08-09 11:01:02,628] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 11:01:02,628] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 11:01:02,634] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 12436 ----
  INFO root [2018-08-09 11:01:02,634] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 11:01:02,635] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 11:01:02,635] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 11:01:02,773] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 11:01:02,774] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 11:01:02,775] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 11:01:02,780] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 11:01:02,781] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 11:01:02,781] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 11:01:02,782] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 11:01:02,844] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 11:01:02,907] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 11:01:02,907] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 11:01:02,911] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 11:01:02,911] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 11:01:03,725] - ---- loginapp is running ----
 DEBUG root [2018-08-09 11:01:03,747] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 11:01:10,024] - Forwarding logs to logger[10.139.89.70:6168/0/0/0]...
 ERROR root [2018-08-09 11:09:39,944] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 11:09:39,947] - The following logs sent to logger failed:
  WARN root [2018-08-09 11:09:39,947] - ==> [2018-08-09 11:09:39 939] TCPPacketReceiver::processPendingEvents(10.139.89.70:6168): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 11:09:39,948] - ==> [2018-08-09 11:09:39 946] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 11:09:40,086] - TCPPacketReceiver::processPendingEvents(10.139.89.70:6170): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 11:09:40,093] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 11:09:40,097] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 11:09:40,100] - onLoginAppShutDown()
  INFO root [2018-08-09 11:09:40,101] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 11:09:40,101] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 11:09:40,101] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 11:09:40,101] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 11:09:40,101] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 11:09:40,102] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 11:09:40,102] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 11:09:40,102] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 11:09:40,102] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 11:09:40,102] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 11:09:40,132] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 11:09:40,133] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 11:09:40,435] - ThreadPool::destroy(): waiting for thread(2)[0x1e9990,0x1e9f40,], try=1
  INFO root [2018-08-09 14:12:13,367] - 
  INFO root [2018-08-09 14:12:13,368] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:12:13,440] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:12:13,440] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:12:13,440] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:12:13,447] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:12:13,447] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:12:13,453] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:6550 )
  INFO root [2018-08-09 14:12:13,453] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:6550, SOMAXCONN=128.
  INFO root [2018-08-09 14:12:13,454] - server-configs:
  INFO root [2018-08-09 14:12:13,454] - 	internalAddr : 10.139.89.70:6550
  INFO root [2018-08-09 14:12:13,454] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:12:13,454] - 	componentID : 9000
  INFO root [2018-08-09 14:12:15,864] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 20684 ----
  INFO root [2018-08-09 14:12:15,865] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:12:15,888] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:12:15,928] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:12:17,514] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:12:17,544] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:12:17,601] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:12:17,763] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:12:17,776] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:12:17,778] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:12:17,784] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:12:18,008] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:12:18,478] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:12:18,479] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:12:18,551] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:12:18,670] - TelnetServer server is running on port 31000
  WARN root [2018-08-09 14:12:19,032] - d:\kbe\kbengine-2.0.0-preview3\kbe\src\server\loginapp\loginapp.cpp:153: Profile scriptCall took 0.12 seconds
  INFO root [2018-08-09 14:12:19,758] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:12:19,759] - Components::process(): Request for the process of identity...
  INFO root [2018-08-09 14:12:26,990] - Components::findComponents: find logger(1)...
  INFO root [2018-08-09 14:12:27,082] - Components::findComponents: found logger, addr:10.139.89.70:6545
  INFO root [2018-08-09 14:12:27,082] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:12:27,082] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:12:27,083] - Components::findComponents: find dbmgr(2)...
  INFO root [2018-08-09 14:12:27,188] - Components::findComponents: found dbmgr, addr:10.139.89.70:6547
  INFO root [2018-08-09 14:12:27,188] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:12:27,188] - Components::addComponent[dbmgr], uid=21326, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:12:27,189] - Components::findComponents: found dbmgr, addr:10.139.89.70:6547
  WARN root [2018-08-09 14:12:28,189] - Forwarding logs to logger[10.139.89.70:6545/0/0/0]...
 ERROR root [2018-08-09 14:20:17,092] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:20:17,098] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:20:17,100] - ==> [2018-08-09 14:20:17 085] TCPPacketReceiver::processPendingEvents(10.139.89.70:6545): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:20:17,100] - ==> [2018-08-09 14:20:17 093] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:20:17,289] - TCPPacketReceiver::processPendingEvents(10.139.89.70:6547): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:20:17,298] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:20:17,305] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:20:17,319] - onLoginAppShutDown()
  INFO root [2018-08-09 14:20:17,320] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:20:17,320] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:20:17,321] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:20:17,321] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:20:17,322] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:20:17,355] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:20:17,355] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:20:17,657] - ThreadPool::destroy(): waiting for thread(2)[0x24da470,0x24da540,], try=1
 DEBUG root [2018-08-09 14:20:18,060] - TPThread::~TPThread(): 0x24da470
 DEBUG root [2018-08-09 14:20:18,061] - TPThread::~TPThread(): 0x24da540
 DEBUG root [2018-08-09 14:20:18,062] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:20:18,079] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-08-09 14:20:18,079] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:20:18,079] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:20:18,080] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:20:18,080] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:20:18,080] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:20:18,080] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:20:18,080] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:20:18,080] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:20:21,283] - 
  INFO root [2018-08-09 14:20:21,296] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:20:21,297] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:20:21,298] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:20:21,298] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:20:21,355] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:20:21,355] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:20:21,360] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:6809 )
  INFO root [2018-08-09 14:20:21,360] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:6809, SOMAXCONN=128.
  INFO root [2018-08-09 14:20:21,361] - server-configs:
  INFO root [2018-08-09 14:20:21,361] - 	internalAddr : 10.139.89.70:6809
  INFO root [2018-08-09 14:20:21,361] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:20:21,361] - 	componentID : 9000
  INFO root [2018-08-09 14:20:21,894] - Components::findLogger: found logger, addr:10.139.89.70:6803
  INFO root [2018-08-09 14:20:21,894] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:20:21,894] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:20:21,903] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 20276 ----
  INFO root [2018-08-09 14:20:21,903] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:20:21,904] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:20:21,905] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:20:22,047] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:20:22,048] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:20:22,049] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:20:22,052] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:20:22,053] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:20:22,053] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:20:22,053] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:20:22,100] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:20:22,158] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:20:22,159] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:20:22,165] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:20:22,166] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:20:22,979] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:20:23,005] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:20:26,607] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20005, errorno=10048
  WARN root [2018-08-09 14:20:29,657] - Forwarding logs to logger[10.139.89.70:6803/0/0/0]...
 ERROR root [2018-08-09 14:23:14,358] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:23:14,366] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:23:14,366] - ==> [2018-08-09 14:23:14 352] TCPPacketReceiver::processPendingEvents(10.139.89.70:6803): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:23:14,367] - ==> [2018-08-09 14:23:14 359] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:23:14,584] - TCPPacketReceiver::processPendingEvents(10.139.89.70:6804): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:23:14,599] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:23:14,629] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:23:14,631] - onLoginAppShutDown()
  INFO root [2018-08-09 14:23:14,631] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:23:14,631] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:23:14,632] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:23:14,632] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:23:14,632] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:23:14,633] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:23:14,633] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:23:14,633] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:23:14,633] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:23:14,633] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:23:14,665] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:23:14,665] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:23:14,966] - ThreadPool::destroy(): waiting for thread(2)[0x2458130,0x2458678,], try=1
 DEBUG root [2018-08-09 14:23:15,368] - TPThread::~TPThread(): 0x2458130
 DEBUG root [2018-08-09 14:23:15,369] - TPThread::~TPThread(): 0x2458678
 DEBUG root [2018-08-09 14:23:15,369] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:23:15,398] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 14:23:15,398] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:23:15,398] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:23:15,398] - UDPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-08-09 14:23:15,398] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:23:15,399] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:23:15,399] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:23:15,399] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:23:15,399] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:23:18,684] - 
  INFO root [2018-08-09 14:23:18,686] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:23:18,687] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:23:18,688] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:23:18,688] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:23:18,727] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:23:18,727] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:23:18,736] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:6889 )
  INFO root [2018-08-09 14:23:18,737] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:6889, SOMAXCONN=128.
  INFO root [2018-08-09 14:23:18,737] - server-configs:
  INFO root [2018-08-09 14:23:18,737] - 	internalAddr : 10.139.89.70:6889
  INFO root [2018-08-09 14:23:18,737] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:23:18,737] - 	componentID : 9000
  INFO root [2018-08-09 14:23:19,315] - Components::findLogger: found logger, addr:10.139.89.70:6883
  INFO root [2018-08-09 14:23:19,315] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:23:19,316] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:23:19,324] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 7660 ----
  INFO root [2018-08-09 14:23:19,325] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:23:19,326] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:23:19,326] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:23:19,476] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:23:19,477] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:23:19,478] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:23:19,483] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:23:19,484] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:23:19,484] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:23:19,485] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:23:19,543] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:23:19,601] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:23:19,601] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:23:19,605] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:23:19,605] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:23:20,428] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:23:20,429] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:23:26,736] - Forwarding logs to logger[10.139.89.70:6883/0/0/0]...
 ERROR root [2018-08-09 14:26:28,342] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:26:28,353] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:26:28,354] - ==> [2018-08-09 14:26:28 342] TCPPacketReceiver::processPendingEvents(10.139.89.70:6883): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:26:28,355] - ==> [2018-08-09 14:26:28 343] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:26:28,580] - TCPPacketReceiver::processPendingEvents(10.139.89.70:6884): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:26:28,585] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:26:28,605] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:26:28,608] - onLoginAppShutDown()
  INFO root [2018-08-09 14:26:28,609] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:26:28,609] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:26:28,610] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:26:28,610] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:26:28,610] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:26:28,611] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:26:28,611] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:26:28,611] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:26:28,612] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:26:28,612] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:26:28,656] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:26:28,657] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:26:28,958] - ThreadPool::destroy(): waiting for thread(2)[0xe194d8,0xe19470,], try=1
 DEBUG root [2018-08-09 14:26:29,365] - TPThread::~TPThread(): 0xe194d8
 DEBUG root [2018-08-09 14:26:29,367] - TPThread::~TPThread(): 0xe19470
 DEBUG root [2018-08-09 14:26:29,367] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:26:29,385] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 14:26:29,385] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:26:29,386] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:26:29,386] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2018-08-09 14:26:29,386] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:26:29,386] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:26:29,386] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:26:29,387] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:26:29,387] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:26:32,970] - 
  INFO root [2018-08-09 14:26:32,981] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:26:32,982] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:26:32,983] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:26:32,983] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:26:33,061] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:26:33,062] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:26:33,071] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7274 )
  INFO root [2018-08-09 14:26:33,072] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7274, SOMAXCONN=128.
  INFO root [2018-08-09 14:26:33,072] - server-configs:
  INFO root [2018-08-09 14:26:33,072] - 	internalAddr : 10.139.89.70:7274
  INFO root [2018-08-09 14:26:33,072] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:26:33,072] - 	componentID : 9000
  INFO root [2018-08-09 14:26:33,619] - Components::findLogger: found logger, addr:10.139.89.70:7264
  INFO root [2018-08-09 14:26:33,619] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:26:33,620] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:26:33,632] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 17452 ----
  INFO root [2018-08-09 14:26:33,633] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:26:33,633] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:26:33,634] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:26:33,785] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:26:33,786] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:26:33,787] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:26:33,793] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:26:33,793] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:26:33,794] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:26:33,795] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:26:33,860] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:26:33,920] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:26:33,921] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:26:33,924] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:26:33,925] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:26:34,766] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:26:34,772] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:26:41,092] - Forwarding logs to logger[10.139.89.70:7264/0/0/0]...
 ERROR root [2018-08-09 14:30:15,301] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:30:15,303] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:30:15,303] - ==> [2018-08-09 14:30:15 301] TCPPacketReceiver::processPendingEvents(10.139.89.70:7264): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:30:15,303] - ==> [2018-08-09 14:30:15 302] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:30:15,483] - TCPPacketReceiver::processPendingEvents(10.139.89.70:7265): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:30:15,496] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:30:15,502] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:30:15,507] - onLoginAppShutDown()
  INFO root [2018-08-09 14:30:15,508] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:30:15,509] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:30:15,511] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:30:15,512] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:30:15,512] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:30:15,514] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:30:15,514] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:30:15,514] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:30:15,515] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:30:15,515] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:30:15,550] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:30:15,551] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:30:15,851] - ThreadPool::destroy(): waiting for thread(2)[0x6d95f8,0x6d92b8,], try=1
 DEBUG root [2018-08-09 14:30:16,255] - TPThread::~TPThread(): 0x6d95f8
 DEBUG root [2018-08-09 14:30:16,260] - TPThread::~TPThread(): 0x6d92b8
 DEBUG root [2018-08-09 14:30:16,261] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:30:16,283] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 14:30:16,283] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:30:16,283] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:30:16,284] - UDPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-08-09 14:30:16,284] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:30:16,284] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:30:16,284] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:30:16,284] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:30:16,284] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:30:19,468] - 
  INFO root [2018-08-09 14:30:19,469] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:30:19,470] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:30:19,470] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:30:19,470] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:30:19,536] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:30:19,536] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:30:19,572] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7424 )
  INFO root [2018-08-09 14:30:19,572] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7424, SOMAXCONN=128.
  INFO root [2018-08-09 14:30:19,573] - server-configs:
  INFO root [2018-08-09 14:30:19,573] - 	internalAddr : 10.139.89.70:7424
  INFO root [2018-08-09 14:30:19,573] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:30:19,573] - 	componentID : 9000
  INFO root [2018-08-09 14:30:20,191] - Components::findLogger: found logger, addr:10.139.89.70:7418
  INFO root [2018-08-09 14:30:20,201] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:30:20,201] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:30:20,208] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14924 ----
  INFO root [2018-08-09 14:30:20,208] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:30:20,208] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:30:20,209] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:30:20,352] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:30:20,353] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:30:20,354] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:30:20,360] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:30:20,360] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:30:20,361] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:30:20,361] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:30:20,430] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:30:20,513] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:30:20,513] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:30:20,532] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:30:20,532] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:30:21,278] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:30:21,282] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:30:24,878] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20607, errorno=10048
  WARN root [2018-08-09 14:30:27,927] - Forwarding logs to logger[10.139.89.70:7418/0/0/0]...
 ERROR root [2018-08-09 14:34:07,919] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:34:07,924] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:34:07,924] - ==> [2018-08-09 14:34:07 910] TCPPacketReceiver::processPendingEvents(10.139.89.70:7418): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:34:07,925] - ==> [2018-08-09 14:34:07 920] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:34:08,100] - TCPPacketReceiver::processPendingEvents(10.139.89.70:7419): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:34:08,105] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:34:08,106] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:34:08,107] - onLoginAppShutDown()
  INFO root [2018-08-09 14:34:08,107] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:34:08,107] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:34:08,108] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:34:08,108] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:34:08,108] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:34:08,108] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:34:08,109] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:34:08,109] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:34:08,109] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:34:08,109] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:34:08,158] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:34:08,159] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:34:08,464] - ThreadPool::destroy(): waiting for thread(2)[0x1698d0,0x169388,], try=1
 DEBUG root [2018-08-09 14:34:08,868] - TPThread::~TPThread(): 0x1698d0
 DEBUG root [2018-08-09 14:34:08,868] - TPThread::~TPThread(): 0x169388
 DEBUG root [2018-08-09 14:34:08,868] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:34:08,888] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 14:34:08,888] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:34:08,888] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:34:08,888] - UDPPacket::destroyObjPool(): size 1.
 DEBUG root [2018-08-09 14:34:08,888] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:34:08,888] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:34:08,889] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:34:08,889] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:34:08,889] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:34:11,536] - 
  INFO root [2018-08-09 14:34:11,544] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:34:11,546] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:34:11,546] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:34:11,546] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:34:11,585] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:34:11,585] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:34:11,593] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7508 )
  INFO root [2018-08-09 14:34:11,594] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7508, SOMAXCONN=128.
  INFO root [2018-08-09 14:34:11,594] - server-configs:
  INFO root [2018-08-09 14:34:11,594] - 	internalAddr : 10.139.89.70:7508
  INFO root [2018-08-09 14:34:11,594] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:34:11,594] - 	componentID : 9000
  INFO root [2018-08-09 14:34:12,212] - Components::findLogger: found logger, addr:10.139.89.70:7503
  INFO root [2018-08-09 14:34:12,213] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:34:12,213] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:34:12,222] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 16532 ----
  INFO root [2018-08-09 14:34:12,223] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:34:12,223] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:34:12,223] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:34:12,373] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:34:12,374] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:34:12,375] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:34:12,379] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:34:12,380] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:34:12,380] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:34:12,382] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:34:12,426] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:34:12,519] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:34:12,520] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:34:12,528] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:34:12,529] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:34:13,254] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:34:13,294] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:34:19,685] - Forwarding logs to logger[10.139.89.70:7503/0/0/0]...
 ERROR root [2018-08-09 14:36:29,854] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:36:29,856] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:36:29,856] - ==> [2018-08-09 14:36:29 846] TCPPacketReceiver::processPendingEvents(10.139.89.70:7503): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:36:29,857] - ==> [2018-08-09 14:36:29 854] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:36:30,052] - TCPPacketReceiver::processPendingEvents(10.139.89.70:7504): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:36:30,054] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:36:30,078] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:36:30,079] - onLoginAppShutDown()
  INFO root [2018-08-09 14:36:30,079] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:36:30,079] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:36:30,079] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:36:30,079] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:36:30,080] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:36:30,105] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:36:30,106] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:36:30,407] - ThreadPool::destroy(): waiting for thread(2)[0xb08110,0xb08930,], try=1
  INFO root [2018-08-09 14:36:33,616] - 
  INFO root [2018-08-09 14:36:33,640] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:36:33,641] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:36:33,641] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:36:33,642] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:36:33,690] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:36:33,690] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:36:33,698] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7591 )
  INFO root [2018-08-09 14:36:33,720] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7591, SOMAXCONN=128.
  INFO root [2018-08-09 14:36:33,721] - server-configs:
  INFO root [2018-08-09 14:36:33,721] - 	internalAddr : 10.139.89.70:7591
  INFO root [2018-08-09 14:36:33,721] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:36:33,721] - 	componentID : 9000
  INFO root [2018-08-09 14:36:34,458] - Components::findLogger: found logger, addr:10.139.89.70:7585
  INFO root [2018-08-09 14:36:34,458] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:36:34,458] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:36:34,464] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 17108 ----
  INFO root [2018-08-09 14:36:34,464] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:36:34,464] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:36:34,465] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:36:34,610] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:36:34,610] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:36:34,611] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:36:34,615] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:36:34,616] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:36:34,616] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:36:34,617] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:36:34,679] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:36:34,739] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:36:34,740] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:36:34,743] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:36:34,744] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:36:35,548] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:36:35,576] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:36:41,861] - Forwarding logs to logger[10.139.89.70:7585/0/0/0]...
 ERROR root [2018-08-09 14:37:36,595] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:37:36,604] - The following logs sent to logger failed:
  WARN root [2018-08-09 14:37:36,606] - ==> [2018-08-09 14:37:36 582] TCPPacketReceiver::processPendingEvents(10.139.89.70:7585): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:37:36,607] - ==> [2018-08-09 14:37:36 596] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 14:37:36,806] - TCPPacketReceiver::processPendingEvents(10.139.89.70:7586): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 14:37:36,813] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 14:37:36,814] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 14:37:36,815] - onLoginAppShutDown()
  INFO root [2018-08-09 14:37:36,815] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 14:37:36,815] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 14:37:36,816] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:37:36,816] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:37:36,816] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:37:36,816] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:37:36,816] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:37:36,817] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:37:36,817] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:37:36,817] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:37:36,864] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 14:37:36,865] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 14:37:37,165] - ThreadPool::destroy(): waiting for thread(2)[0xab92b8,0xab9798,], try=1
 DEBUG root [2018-08-09 14:37:37,569] - TPThread::~TPThread(): 0xab92b8
 DEBUG root [2018-08-09 14:37:37,570] - TPThread::~TPThread(): 0xab9798
 DEBUG root [2018-08-09 14:37:37,571] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 14:37:37,591] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 14:37:37,592] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 14:37:37,592] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 14:37:37,592] - UDPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:37:37,592] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 14:37:37,593] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:37:37,593] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 14:37:37,593] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 14:37:37,593] - loginapp(9000) has shut down.
  INFO root [2018-08-09 14:37:41,104] - 
  INFO root [2018-08-09 14:37:41,105] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:37:41,106] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:37:41,107] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:37:41,107] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:37:41,115] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:37:41,116] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:37:41,124] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:7660 )
  INFO root [2018-08-09 14:37:41,125] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:7660, SOMAXCONN=128.
  INFO root [2018-08-09 14:37:41,125] - server-configs:
  INFO root [2018-08-09 14:37:41,125] - 	internalAddr : 10.139.89.70:7660
  INFO root [2018-08-09 14:37:41,125] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:37:41,125] - 	componentID : 9000
  INFO root [2018-08-09 14:37:41,722] - Components::findLogger: found logger, addr:10.139.89.70:7654
  INFO root [2018-08-09 14:37:41,722] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:37:41,722] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:37:41,728] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 8120 ----
  INFO root [2018-08-09 14:37:41,728] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:37:41,728] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:37:41,729] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:37:41,860] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:37:41,860] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:37:41,861] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:37:41,864] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:37:41,865] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:37:41,865] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:37:41,865] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:37:41,899] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:37:41,937] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:37:41,938] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:37:41,940] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:37:41,941] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:37:42,529] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:37:42,546] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:37:49,090] - Forwarding logs to logger[10.139.89.70:7654/0/0/0]...
  INFO root [2018-08-09 14:41:24,922] - 
  INFO root [2018-08-09 14:41:24,943] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 14:41:24,944] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 14:41:24,944] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 14:41:24,945] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 14:41:24,983] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 14:41:24,983] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 14:41:24,988] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:9074 )
  INFO root [2018-08-09 14:41:24,988] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:9074, SOMAXCONN=128.
  INFO root [2018-08-09 14:41:24,988] - server-configs:
  INFO root [2018-08-09 14:41:24,989] - 	internalAddr : 10.139.89.70:9074
  INFO root [2018-08-09 14:41:24,989] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 14:41:24,989] - 	componentID : 9000
  INFO root [2018-08-09 14:41:25,905] - Components::findLogger: found logger, addr:10.139.89.70:9029
  INFO root [2018-08-09 14:41:25,906] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 14:41:25,906] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 14:41:25,914] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 14864 ----
  INFO root [2018-08-09 14:41:25,914] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 14:41:25,915] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 14:41:25,915] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 14:41:26,054] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 14:41:26,055] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 14:41:26,055] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 14:41:26,058] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 14:41:26,059] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 14:41:26,059] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 14:41:26,060] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 14:41:26,113] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 14:41:26,169] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 14:41:26,169] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 14:41:26,173] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 14:41:26,174] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 14:41:26,888] - ---- loginapp is running ----
 DEBUG root [2018-08-09 14:41:26,891] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 14:41:33,153] - Forwarding logs to logger[10.139.89.70:9029/0/0/0]...
 ERROR root [2018-08-09 16:14:41,184] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 16:14:41,194] - The following logs sent to logger failed:
  WARN root [2018-08-09 16:14:41,195] - ==> [2018-08-09 16:14:41 183] TCPPacketReceiver::processPendingEvents(10.139.89.70:9029): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 16:14:41,195] - ==> [2018-08-09 16:14:41 185] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 16:14:41,341] - TCPPacketReceiver::processPendingEvents(10.139.89.70:9030): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 16:14:41,351] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 16:14:41,353] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 16:14:41,362] - onLoginAppShutDown()
  INFO root [2018-08-09 16:14:41,362] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 16:14:41,362] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 16:14:41,365] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 16:14:41,366] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 16:14:41,367] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 16:14:41,367] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 16:14:41,367] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 16:14:41,368] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 16:14:41,368] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 16:14:41,368] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 16:14:41,408] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 16:14:41,412] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 16:14:41,715] - ThreadPool::destroy(): waiting for thread(2)[0x8be10,0x8c288,], try=1
 DEBUG root [2018-08-09 16:14:42,131] - TPThread::~TPThread(): 0x8be10
 DEBUG root [2018-08-09 16:14:42,131] - TPThread::~TPThread(): 0x8c288
 DEBUG root [2018-08-09 16:14:42,131] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 16:14:42,162] - Bundle::destroyObjPool(): size 12.
 DEBUG root [2018-08-09 16:14:42,162] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 16:14:42,163] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 16:14:42,164] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2018-08-09 16:14:42,164] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 16:14:42,164] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 16:14:42,164] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 16:14:42,164] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 16:14:42,164] - loginapp(9000) has shut down.
  INFO root [2018-08-09 16:14:45,088] - 
  INFO root [2018-08-09 16:14:45,089] - -----------------------------------------------------------------------------------------


  INFO root [2018-08-09 16:14:45,090] - Resmgr::initialize: KBE_ROOT=D:/kbe/kbengine-2.0.0-preview3/
  INFO root [2018-08-09 16:14:45,090] - Resmgr::initialize: KBE_RES_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/res/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/scripts/;D:/kbe/kbengine-2.0.0-preview3/assets_Battle of Gods/res/
  INFO root [2018-08-09 16:14:45,090] - Resmgr::initialize: KBE_BIN_PATH=D:/kbe/kbengine-2.0.0-preview3/kbe/bin/server/
  INFO root [2018-08-09 16:14:45,132] - NetworkInterface::initialize(EXTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:20013 )
  INFO root [2018-08-09 16:14:45,133] - NetworkInterface::initialize(EXTERNAL): address 10.139.89.70:20013, SOMAXCONN=128.
  INFO root [2018-08-09 16:14:45,177] - NetworkInterface::initialize(INTERNAL): bound to all interfaces with default route interface on 10.139.89.70 ( 10.139.89.70:2549 )
  INFO root [2018-08-09 16:14:45,178] - NetworkInterface::initialize(INTERNAL): address 10.139.89.70:2549, SOMAXCONN=128.
  INFO root [2018-08-09 16:14:45,178] - server-configs:
  INFO root [2018-08-09 16:14:45,178] - 	internalAddr : 10.139.89.70:2549
  INFO root [2018-08-09 16:14:45,178] - 	externalAddr : 10.139.89.70:20013
  INFO root [2018-08-09 16:14:45,179] - 	componentID : 9000
  INFO root [2018-08-09 16:14:45,936] - Components::findLogger: found logger, addr:10.139.89.70:2516
  INFO root [2018-08-09 16:14:45,937] - Components::addComponent: reset orderLog, uid=21326!
  INFO root [2018-08-09 16:14:45,937] - Components::addComponent[logger], uid=21326, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2018-08-09 16:14:45,945] - ---- loginapp Version: 2.0.0. ScriptVersion: 0.1.0. Protocol: 509F1315D4496C9A9FD187B287F2023C. Config: Debug X86. Built: 23:19:23 May 26 2018. AppID: 9000. UID: 21326. PID: 18700 ----
  INFO root [2018-08-09 16:14:45,946] - Server : Intel(R) Core(TM) i5-4210H CPU @ 2.90GHz with 2097151kB RAM
  INFO root [2018-08-09 16:14:45,946] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2018-08-09 16:14:45,947] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2018-08-09 16:14:46,132] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 16:14:46,133] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 16:14:46,133] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 16:14:46,142] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 16:14:46,142] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 16:14:46,143] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 16:14:46,143] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 16:14:46,217] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 16:14:46,307] - Script::install(): is successfully, Python=(3.4.2 (default, May 26 2018, 23:19:20) [MSC v.1913 32 bit (Intel)])!
  INFO root [2018-08-09 16:14:46,307] - Script::install(): KBExtra is successfully!
S_INFO root [2018-08-09 16:14:46,311] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2018-08-09 16:14:46,312] - TelnetServer server is running on port 31000
  INFO root [2018-08-09 16:14:46,909] - ---- loginapp is running ----
 DEBUG root [2018-08-09 16:14:46,909] - Components::process(): Request for the process of identity...
  WARN root [2018-08-09 16:14:53,198] - Forwarding logs to logger[10.139.89.70:2516/0/0/0]...
 ERROR root [2018-08-09 16:16:41,408] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 16:16:41,415] - The following logs sent to logger failed:
  WARN root [2018-08-09 16:16:41,416] - ==> [2018-08-09 16:16:41 405] TCPPacketReceiver::processPendingEvents(10.139.89.70:2516): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 16:16:41,416] - ==> [2018-08-09 16:16:41 409] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2018-08-09 16:16:41,582] - TCPPacketReceiver::processPendingEvents(10.139.89.70:2541): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2018-08-09 16:16:41,585] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2018-08-09 16:16:41,585] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2018-08-09 16:16:41,586] - onLoginAppShutDown()
  INFO root [2018-08-09 16:16:41,586] - Shutdowner::onShutdown: shutting down
  INFO root [2018-08-09 16:16:41,586] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2018-08-09 16:16:41,586] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2018-08-09 16:16:41,587] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2018-08-09 16:16:41,618] - Script::uninstall(): is successfully!
 DEBUG root [2018-08-09 16:16:41,618] - ThreadPool::destroy(): starting size 2.
  WARN root [2018-08-09 16:16:41,919] - ThreadPool::destroy(): waiting for thread(2)[0xc8820,0xc88f0,], try=1
 DEBUG root [2018-08-09 16:16:42,321] - TPThread::~TPThread(): 0xc8820
 DEBUG root [2018-08-09 16:16:42,321] - TPThread::~TPThread(): 0xc88f0
 DEBUG root [2018-08-09 16:16:42,321] - ThreadPool::destroy(): successfully!
 DEBUG root [2018-08-09 16:16:42,351] - Bundle::destroyObjPool(): size 28.
 DEBUG root [2018-08-09 16:16:42,351] - Channel::destroyObjPool(): size 14.
 DEBUG root [2018-08-09 16:16:42,352] - TCPPacket::destroyObjPool(): size 11.
 DEBUG root [2018-08-09 16:16:42,352] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2018-08-09 16:16:42,352] - EndPoint::destroyObjPool(): size 13.
 DEBUG root [2018-08-09 16:16:42,352] - Address::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 16:16:42,352] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2018-08-09 16:16:42,353] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2018-08-09 16:16:42,353] - loginapp(9000) has shut down.
